package backend.util;

class LogUtil {
  public static function buildSystemInfo():String
  {
    var fullContents = 'Generated by: Mixtape Engine\n';
    fullContents += 'System timestamp: ${Date.now().toString()}\n';
    var driverInfo = FlxG?.stage?.context3D?.driverInfo ?? 'N/A';
    fullContents += 'Driver info: ${driverInfo}\n';
    #if sys
    fullContents += 'Platform: ${Sys.systemName()}\n';
    #end
    fullContents += '\n';

    fullContents += '=====================\n';

    fullContents += '\n';

    fullContents += MemoryUtilBase.buildGCInfo();

    return fullContents;
  }
}
