package objects;

import backend.NoteTypesConfig;
import backend.animation.PsychAnimationController;
import flixel.math.FlxRect;
import objects.StrumNote;
import objects.playfields.PlayField;
import shaders.RGBPalette.RGBShaderReference;
import shaders.RGBPalette;
import states.editors.ChartingState;

typedef EventNote = {
	strumTime:Float,
	event:String,
	value1:String,
	value2:String
}

typedef NoteSplashData = {
	disabled:Bool,
	texture:String,
	useGlobalShader:Bool, //breaks r/g/b but makes it copy default colors for your custom note
	useRGBShader:Bool,
	antialiasing:Bool,
	r:FlxColor,
	g:FlxColor,
	b:FlxColor,
	a:Float
}

enum abstract SustainPart(Int) from Int to Int
{
	var TAP = -1; // Not a sustain
	var HEAD = 0; // TapNote at the start of a sustain
	var PART = 1;
	var END = 2;
}

/**
 * The note object used as a data structure to spawn and manage notes during gameplay.
 *
 * If you want to make a custom note type, you should search for: "function set_noteType"
**/
class Note extends NoteObject
{
	// Start of Extra Keys

	public static var gfxLetter:Array<String> = [
		'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
		'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'
	];

	//EK Data
	public static var ammo:Array<Int> = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];
	public static var scales:Array<Float> = [0.9, 0.85, 0.8, 0.7, 0.66, 0.6, 0.55, 0.50, 0.46, 0.39, 0.36, 0.32, 0.31, 0.31, 0.3, 0.26, 0.26, 0.22];
	public static var lessX:Array<Int> = [0, 0, 0, 0, 0, 8, 7, 8, 8, 7, 6, 6, 8, 7, 6, 7, 6, 6];
	public static var separator:Array<Int> = [-50, 99, 99, 1, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 7, 6, 5, 4];
	public static var xtra:Array<Int> = [1, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
	public static var posRest:Array<Int> = [0, 0, 0, 0, 25, 32,46, 52, 60, 40, 45, 30, 30, 29,72, 37, 61, 80];
	public static var gridSizes:Array<Int> = [40, 40, 40, 40, 40, 40, 40, 40, 40, 35, 30, 25, 25, 20, 20, 20, 20, 15];
	public static var xPosButBetter:Array<Float> = [2, 2, 2, 2, 1.5, 1.1, 1.1, 1, 1, 2, 2, 2, 2, 1.2, 2, 2, 2, 2];
	public static var xPosButBetter2:Array<Float> = [1, 1, 1, 1, 1.1, 1.2, 1.3, 1.5, 1.7, 1, 1, 1, 1, 2.9, 1, 1, 1, 1];
	public static var xPosButBetterOff:Array<Float> = [100, 100, 100, 100, 130, 250, 300, 300, 300, 100, 100, 100, 100, 250, 100, 100, 100, 100];
	public static var offsets:Array<Dynamic> = [[20, 10], [10, 10], [10, 10], [10, 10], [10, 10], [10, 10], [10, 10], [10, 10], [10, 10], [10, 20], [10, 10], [10, 10], [10, 10], [10, 10], [10, 10],[10, 10],[10, 10], [10, 10]];
	public static var noteSplashScales:Array<Float> = [1.3, 1.2, 1.1, 1, 1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.3, 0.3, 0.2, 0.18, 0.18, 0.15];
	public static var noteSplashOffsets:Map<Int, Array<Int>> = [0 => [20, 10], 9 => [10, 20]];

	public static var minMania:Int = 0;
	public static var maxMania:Int = 17;
	public static var defaultMania:Int = 3;
	public var downscrollNote:Bool = ClientPrefs.data.downScroll;
	public var baseAlpha:Float = 1;
	public var autoGenerated:Bool = false;
	public static var pixelNotesDivisionValue:Array<Int> = [4, 18];

	public var noteReflection(get, set):Dynamic;

	private function get_noteReflection():Dynamic {
		return try {
				{
					strumTime: this.strumTime,
					mustPress: this.mustPress,
					canBeHit: this.canBeHit,
					tooLate: this.tooLate,
					botNote: this.botNote,
					wasGoodHit: this.wasGoodHit,
					missed: this.missed,
					ignoreNote: this.ignoreNote,
					hitByOpponent: this.hitByOpponent,
					noteType: this.noteType,
					alpha: this.alpha,
					owner: this.owner,
					x: this.x,
					y: this.y,
					rgb: {
						r: this.rgbShader.r,
						g: this.rgbShader.g,
						b: this.rgbShader.b
					},
					texture: this.texture
				}
			} catch (e:Dynamic) {
				// trace("An error occurred while getting the value of note.");
				null;
			}
	}

	private function set_noteReflection(value:Dynamic):Dynamic {
		try {
			if (value.strumTime != null) this.strumTime = value.strumTime;
		} catch (e:Dynamic) {
			if (Std.is(value.strumTime, Float)) {
				trace("An error occurred while setting the value of strumTime.");
			} else {
				trace("Cannot set strumTime to " + value.strumTime + ", because strumTime is Float and your value is " + Type.typeof(value.strumTime) + ".");
			}
		}

		try {
			if (value.mustPress != null) this.mustPress = value.mustPress;
		} catch (e:Dynamic) {
			if (Std.is(value.mustPress, Bool)) {
				trace("An error occurred while setting the value of mustPress.");
			} else {
				trace("Cannot set mustPress to " + value.mustPress + ", because mustPress is Bool and your value is " + Type.typeof(value.mustPress) + ".");
			}
		}

		try {
			if (value.canBeHit != null) this.canBeHit = value.canBeHit;
		} catch (e:Dynamic) {
			if (Std.is(value.canBeHit, Bool)) {
				trace("An error occurred while setting the value of canBeHit.");
			} else {
				trace("Cannot set canBeHit to " + value.canBeHit + ", because canBeHit is Bool and your value is " + Type.typeof(value.canBeHit) + ".");
			}
		}

		try {
			if (value.tooLate != null) this.tooLate = value.tooLate;
		} catch (e:Dynamic) {
			if (Std.is(value.tooLate, Bool)) {
				trace("An error occurred while setting the value of tooLate.");
			} else {
				trace("Cannot set tooLate to " + value.tooLate + ", because tooLate is Bool and your value is " + Type.typeof(value.tooLate) + ".");
			}
		}

		try {
			if (value.wasGoodHit != null) this.wasGoodHit = value.wasGoodHit;
		} catch (e:Dynamic) {
			if (Std.is(value.wasGoodHit, Bool)) {
				trace("An error occurred while setting the value of wasGoodHit.");
			} else {
				trace("Cannot set wasGoodHit to " + value.wasGoodHit + ", because wasGoodHit is Bool and your value is " + Type.typeof(value.wasGoodHit) + ".");
			}
		}

		try {
			if (value.missed != null) this.missed = value.missed;
		} catch (e:Dynamic) {
			if (Std.is(value.missed, Bool)) {
				trace("An error occurred while setting the value of missed.");
			} else {
				trace("Cannot set missed to " + value.missed + ", because missed is Bool and your value is " + Type.typeof(value.missed) + ".");
			}
		}

		try {
			if (value.ignoreNote != null) this.ignoreNote = value.ignoreNote;
		} catch (e:Dynamic) {
			if (Std.is(value.ignoreNote, Bool)) {
				trace("An error occurred while setting the value of ignoreNote.");
			} else {
				trace("Cannot set ignoreNote to " + value.ignoreNote + ", because ignoreNote is Bool and your value is " + Type.typeof(value.ignoreNote) + ".");
			}
		}

		try {
			if (value.hitByOpponent != null) this.hitByOpponent = value.hitByOpponent;
		} catch (e:Dynamic) {
			if (Std.is(value.hitByOpponent, Bool)) {
				trace("An error occurred while setting the value of hitByOpponent.");
			} else {
				trace("Cannot set hitByOpponent to " + value.hitByOpponent + ", because hitByOpponent is Bool and your value is " + Type.typeof(value.hitByOpponent) + ".");
			}
		}

		try {
			if (value.noteType != null) this.noteType = value.noteType;
		} catch (e:Dynamic) {
			if (Std.is(value.noteType, String)) {
				trace("An error occurred while setting the value of noteType.");
			} else {
				trace("Cannot set noteType to " + value.noteType + ", because noteType is String and your value is " + Type.typeof(value.noteType) + ".");
			}
		}

		try {
			if (value.alpha != null) this.alpha = value.alpha;
		} catch (e:Dynamic) {
			if (Std.is(value.alpha, Float)) {
				trace("An error occurred while setting the value of alpha.");
			} else {
				trace("Cannot set alpha to " + value.alpha + ", because alpha is Float and your value is " + Type.typeof(value.alpha) + ".");
			}
		}

		try {
			if (value.x != null) this.x = value.x;
		} catch (e:Dynamic) {
			if (Std.is(value.x, Float)) {
				trace("An error occurred while setting the value of x.");
			} else {
				trace("Cannot set x to " + value.x + ", because x is Float and your value is " + Type.typeof(value.x) + ".");
			}
		}

		try {
			if (value.y != null) this.y = value.y;
		} catch (e:Dynamic) {
			if (Std.is(value.y, Float)) {
				trace("An error occurred while setting the value of y.");
			} else {
				trace("Cannot set y to " + value.y + ", because y is Float and your value is " + Type.typeof(value.y) + ".");
			}
		}

		try {
			if (value.rgb != null) {
				if (value.rgb.r != null) {
					try {
						// Store temporarily if in preload mode, otherwise set directly
						if (isInPreloadMode && tempRGBColors != null) {
							tempRGBColors.r = value.rgb.r;
						} else {
							this.rgbShader.r = value.rgb.r;
						}
					} catch (e:Dynamic) {
						if (Std.is(value.rgb.r, Int)) {
							trace("An error occurred while setting the value of rgb.r.");
						} else {
							trace("Cannot set rgb.r to " + value.rgb.r + ", because rgb.r is Int and your value is " + Type.typeof(value.rgb.r) + ".");
						}
					}
				}
				if (value.rgb.g != null) {
					try {
						// Store temporarily if in preload mode, otherwise set directly
						if (isInPreloadMode && tempRGBColors != null) {
							tempRGBColors.g = value.rgb.g;
						} else {
							this.rgbShader.g = value.rgb.g;
						}
					} catch (e:Dynamic) {
						if (Std.is(value.rgb.g, Int)) {
							trace("An error occurred while setting the value of rgb.g.");
						} else {
							trace("Cannot set rgb.g to " + value.rgb.g + ", because rgb.g is Int and your value is " + Type.typeof(value.rgb.g) + ".");
						}
					}
				}
				if (value.rgb.b != null) {
					try {
						// Store temporarily if in preload mode, otherwise set directly
						if (isInPreloadMode && tempRGBColors != null) {
							tempRGBColors.b = value.rgb.b;
						} else {
							this.rgbShader.b = value.rgb.b;
						}
					} catch (e:Dynamic) {
						if (Std.is(value.rgb.b, Int)) {
							trace("An error occurred while setting the value of rgb.b.");
						} else {
							trace("Cannot set rgb.b to " + value.rgb.b + ", because rgb.b is Int and your value is " + Type.typeof(value.rgb.b) + ".");
						}
					}
				}
			}
		} catch (e:Dynamic) {
			trace("An error occurred while setting the value of rgb.");
		}

		try {
			if (value.texture != null) this.texture = value.texture;
		} catch (e:Dynamic) {
			if (Std.is(value.texture, String)) {
				trace("An error occurred while setting the value of texture.");
			} else {
				trace("Cannot set texture to " + value.texture + ", because texture is String and your value is " + Type.typeof(value.texture) + ".");
			}
		}

		// Handle extra variables
		if (value != null) {
			for (field in Reflect.fields(value)) {
				if (!Reflect.hasField(this, field) && !Reflect.hasField(value, field)) {
					if (extraData == null) extraData = new Map<String, Dynamic>();
					extraData.set(field, Reflect.field(value, field));
					trace("This variable '" + field + "' of type '" + Type.typeof(Reflect.field(value, field)) + "' doesn't exist.");
				} else {
					try {
						Reflect.setField(this, field, Reflect.field(value, field));
					} catch (e:Dynamic) {
						if (Type.typeof(Reflect.field(this, field)) == Type.typeof(Reflect.field(value, field))) {
							trace("An error occurred while setting the value of " + field + ".");
						} else {
							trace("Cannot set " + field + " to " + Reflect.field(value, field) + ", because " + field + " is " + Type.typeof(Reflect.field(this, field)) + " and your value is " + Type.typeof(Reflect.field(value, field)) + ".");
						}
					}
				}
			}
			// Remove the map from the object
			extraData = null;
		}

		return value;
	}



	public static var minManiaUI_integer:Int = minMania + 1;
	public static var maxManiaUI_integer:Int = maxMania + 1;

	public static var xmlMax:Int = 17; // This specifies the max of the splashes can go

	public static var keysShit:Map<Int, Map<String, Dynamic>> = [
		0 => [
			"letters" => ["E"],
			"anims" => ["UP"],
			"singAnims" => ["singUP"],
			"strumAnims" => ["SPACE"],
			"pixelAnimIndex" => [4],
			"colArray" => [2]
		],
		1 => [
				"letters" => ["A", "D"],
				"anims" => ["LEFT", "RIGHT"],
				"singAnims" => ["singLEFT", "singRIGHT"],
				"strumAnims" => ["LEFT", "RIGHT"],
				"pixelAnimIndex" => [0, 3],
				"colArray" => [0, 3]
			],
		2 => [
				"letters" => ["A", "E", "D"],
				"anims" => ["LEFT", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "SPACE", "RIGHT"],
				"pixelAnimIndex" => [0, 4, 3],
				"colArray" => [0, 2, 3]
			],
		3 => [
				"letters" => ["A", "B", "C", "D"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3],
				"colArray" => [0, 1, 2, 3]
			],

		4 => [
				"letters" => ["A", "B", "E", "C", "D"],
				"anims" => ["LEFT", "DOWN", "UP", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "SPACE", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 4, 2, 3],
				"colArray" => [0, 1, 2, 2, 3]
			],
		5 => [
				"letters" => ["A", "C", "D", "F", "B", "I"],
				"anims" => ["LEFT", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT"],
				"singAnims" => ["singLEFT", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singRIGHT"],
				"strumAnims" => ["LEFT", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT"],
				"pixelAnimIndex" => [0, 2, 3, 5, 1, 8],
				"colArray" => [0, 2, 3, 0, 1, 3]
			],
		6 => [
				"letters" => ["A", "C", "D", "E", "F", "B", "I"],
				"anims" => ["LEFT", "UP", "RIGHT", "UP", "LEFT", "DOWN", "RIGHT"],
				"singAnims" => ["singLEFT", "singUP", "singRIGHT", "singUP", "singLEFT", "singDOWN", "singRIGHT"],
				"strumAnims" => ["LEFT", "UP", "RIGHT", "SPACE", "LEFT", "DOWN", "RIGHT"],
				"pixelAnimIndex" => [0, 2, 3, 4, 5, 1, 8],
				"colArray" => [0, 2, 3, 2, 0, 1, 3]
			],
		7 => [
				"letters" => ["A", "B", "C", "D", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 3]
			],
		8 => [
				"letters" => ["A", "B", "C", "D", "E", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "UP", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singUP", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "SPACE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 4, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 2, 0, 1, 2, 3]
			],
		9 => [
				"letters" => ["A", "B", "C", "D", "E", "N", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "UP", "UP", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singUP", "singUP", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "SPACE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 4, 13, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 2, 2, 0, 1, 2, 3]
			],
		10 => [
				"letters" => ["A", "B", "C", "D", "J", "E", "M", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "SPACE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 4, 12, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 2, 3, 0, 1, 2, 3]
			],
		11 => [
				"letters" => ["A", "B", "C", "D", "J", "K", "L", "M", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 10, 11, 12, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
			],
		12 => [
				"letters" => ["A", "B", "C", "D", "J", "K", "N", "L", "M", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 10, 13, 11, 12, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 2, 3, 0, 1, 2, 3]
			],
		13 => [
				"letters" => ["A", "B", "C", "D", "J", "K", "E", "N", "L", "M", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "UP", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singUP", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "CIRCLE", "SPACE", "CIRCLE", "CIRCLE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 10, 4, 13, 11, 12, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 2, 2, 3, 0, 1, 2, 3]
			],
		14 => [
				"letters" => ["A", "B", "C", "D", "J", "K", "E", "N", "E", "L", "M", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "UP", "UP", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singUP", "singUP", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "CIRCLE", "SPACE", "CIRCLE", "SPACE", "CIRCLE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 10, 4, 13, 4, 11, 12, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 2, 2, 2, 3, 0, 1, 2, 3]
			],
		15 => [
				"letters" => ["A", "B", "C", "D", "J", "K", "L", "M", "O", "P", "Q", "R", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 10, 11, 12, 14, 15, 16, 17, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
			],
		16 => [
				"letters" => ["A", "B", "C", "D", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "F", "G", "H", "I"],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 9, 10, 11, 12, 13, 14, 15, 16, 17, 5, 6, 7, 8],
				"colArray" => [0, 1, 2, 3, 0, 1, 2, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
		],
		17 => [
				"letters" => ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
				'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'],
				"anims" => ["LEFT", "DOWN", "UP", "RIGHT", "UP", "LEFT", "DOWN", "UP", "RIGHT",
				"LEFT", "DOWN", "UP", "RIGHT", "UP", "LEFT", "DOWN", "UP", "RIGHT"],
				"singAnims" => ["singLEFT", "singDOWN", "singUP", "singRIGHT", "singUP", "singLEFT", "singDOWN", "singUP", "singRIGHT",
				"singLEFT", "singDOWN", "singUP", "singRIGHT", "singUP", "singLEFT", "singDOWN", "singUP", "singRIGHT"],
				"strumAnims" => ["LEFT", "DOWN", "UP", "RIGHT", "SPACE", "LEFT", "DOWN", "UP", "RIGHT",
				"LEFT", "DOWN", "UP", "RIGHT", "CIRCLE", "LEFT", "DOWN", "UP", "RIGHT"],
				"pixelAnimIndex" => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
				"colArray" => [0, 1, 2, 3, 2, 0, 1, 2, 3, 0, 1, 2, 3, 2, 0, 1, 2, 3]
		],
	];

	public var botNote:Bool = false;

	public static var pixelScales:Array<Float> = [
        1.2, //1k
        1.15, //2k
        1.1, //3k
        1, //4k
        0.9, //5k
        0.83, //6k
        0.8, //7k
        0.74, //8k
        0.7, //9k
        0.6, //10k
        0.55,//11k
        0.5, //12k
        0.48, //13k
        0.48, //14k
        0.42, //15k
        0.38, //16k
        0.38, //17k
        0.32 //18k
    ];

	// End of Extra Keys

	//This is needed for the hardcoded note types to appear on the Chart Editor,
	//It's also used for backwards compatibility with 0.1 - 0.3.2 charts.
	public static final defaultNoteTypes:Array<String> = [
		'', //Always leave this one empty pls
		'Alt Animation',
		'Hey!',
		'Hurt Note',
		'GF Sing',
		'EX Note',
		'No Animation',
		'Botplay Note',
		'sakura-joint',
		'sakura-bf1',
		'sakura-bf2'
	];
	public var strumTime:Float = 0;

	public var row:Int = 0;

	public var mustPress:Bool = false;
	public var canBeHit:Bool = false;
	public var tooLate:Bool = false;

	public var wasGoodHit:Bool = false;
	public var missed:Bool = false;

	public var ignoreNote:Bool = false;
	public var hitByOpponent:Bool = false;
	public var noteWasHit:Bool = false;
	public var prevNote:Note;
	public var nextNote:Note;

	public var spawned:Bool = false;

	public var tail:Array<Note> = []; // for sustains
	public var parent:Note;

	public var blockHit:Bool = false; // only works for player
	public var forceBlockHit:Bool = false;

	public var sustainLength:Float = 0;
	public var isSustainNote:Bool = false;
	public var noteType(default, set):String = null;

	public var eventName:String = '';
	public var eventLength:Int = 0;
	public var eventVal1:String = '';
	public var eventVal2:String = '';

	public var rgbShader:RGBShaderReference;
	// Temporary RGB storage for preload mode
	private var tempRGBData:{noteData:Int, disableRGB:Bool, isPixelStage:Bool, postfix:String} = null;
	// Temporary RGB color values for preload mode
	private var tempRGBColors:{r:FlxColor, g:FlxColor, b:FlxColor} = null;
	private var isInPreloadMode:Bool = false;
	public static var globalRgbShaders:Array<RGBPalette> = [];
	public var inEditor:Bool = false;

	public var animSuffix:String = '';
	public var gfNote:Bool = false;
	public var earlyHitMult:Float = 1;
	public var lateHitMult:Float = 1;
	public var lowPriority:Bool = false;

	public static var SUSTAIN_SIZE:Int = 44;
	public static var swagWidth:Float = 160 * 0.7;
	public static var swagWidthAlt:Float = 160; //For ModManager
	public static var colArray:Array<String> = ['purple', 'blue', 'green', 'red'];
	public static var colArrayAlt:Array<String> = ['purple', 'blue', 'green', 'red', 'white', 'yellow', 'violet', 'black', 'dark'];
	public static var defaultNoteSkin(default, never):String = 'noteSkins/NOTE_assets';

	public var noteSplashData:NoteSplashData = {
		disabled: false,
		texture: null,
		antialiasing: !PlayState.isPixelStage,
		useGlobalShader: false,
		useRGBShader: (PlayState.SONG != null) ? !(PlayState.SONG.disableNoteRGB == true) : true,
		r: -1,
		g: -1,
		b: -1,
		a: ClientPrefs.data.splashAlpha
	};

	public var offsetAngle:Float = 0;
	public var multSpeed(default, set):Float = 1;
	public var beat:Float = 0;
	public var copyX:Bool = true;
	public var copyY:Bool = true;
	public var copyAlpha:Bool = true;
	public var alphaLimit:Float = 1;
	public var alphaMod:Float = 1;
	public var alphaMod2:Float = 1; // TODO: unhardcode this shit lmao
	@:noCompletion private static function set_swagWidth(val:Float){
		halfWidth = val * 0.5;
		return val;
	}
	public static var halfWidth(default, null):Float = swagWidth * 0.5;

	public var hitHealth:Float = 0.02;
	public var missHealth:Float = 0.1;
	public var rating:String = 'unknown';
	public var ratingMod:Float = 0; //9 = unknown, 0.25 = shit, 0.5 = bad, 0.75 = good, 1 = sick
	public var ratingDisabled:Bool = false;

	public var texture(default, set):String = null;

	public var noAnimation:Bool = false;
	public var noMissAnimation:Bool = false;
	public var hitCausesMiss:Bool = false;
	public var distance:Float = 2000; //plan on doing scroll directions soon -bb

	//Archipelago
	//TODO: Make this it's own object to help de-clutter Note
	//Maybe even make note like BaseNote or something to make hardcoded sub-notetypes or something
	private var isCheck:Bool = false;
	private var checkInfo:{note:Note, loc:Int};
	public var isMine:Bool = false;
	public var isAlert:Bool = false;
	public var isHeal:Bool = false;
	public var isFreeze:Bool = false;
	public var isFakeHeal:Bool = false;
	var justMixedUp:Bool = false;
	public var trueNoteData:Int = 0;
	public var specialNote:Bool = false;
	public var ignoreMiss:Bool = false;
	public var spinAmount:Float = 0;
	public var rootNote:Note;
	var posTween:FlxTween;
	public var formerPress:Bool = false;

	//Action Engine Stuff
	public var noteIndex:Int = -1;

	//Mixtape Stuff
	// editor stuff for hit sounds
	public var editorHitBeat:Float = 0;
	public var holdType:SustainPart = TAP;
	public var parentNote:Note;
	public var childrenNotes:Array<Note> = [];
	var ogW:Float;
	var ogH:Float;
	public static var defaultWidth:Float = 0;
	public static var defaultHeight:Float = 0;
	public static var spriteScale:Float = 0.7;
	public var exNote:Bool = false;
	public var ghostNote:Bool = false;
	public var changeAnim:Bool = true;
	public var changeColSwap:Bool = true;
	public var isParent:Bool; // ke input shits
	public var childs:Array<Note> = [];
	public var spotInLine:Int = 0;
	public var susActive:Bool = true;
	public var customHealthHit:Bool = false;
	public var centerNote:Bool = false;
	public var hitboxMultiplier:Float = 1;
	public var cod:String = null;
	public var scrollSpeed(default, set):Float = 0;
	public var garbage:Bool = false; // if this is true, the note will be removed in the next update cycle
	public var holdingTime:Float = 0;
	public var causedMiss:Bool = false;
	public var unhitTail:Array<Note> = [];
	public var tripProgress:Float = 1;
	public var isHeld:Bool = false;
	/** The maximum amount of time you can release a hold before it counts as a miss**/
	public var maxReleaseTime:Float = 0.75;
	public var typeOffsetX:Float = 0; // used to offset notes, mainly for note types. use in place of offset.x and offset.y when offsetting notetypes
	public var typeOffsetY:Float = 0;
	public var requiresTap:Bool = true;
	public var isRoll:Bool = false;
	public var holdGlow:Bool = true; // Whether holds should "glow" / increase in alpha when held
	public var visualTime:Float = 0;
	public var fieldIndex:Int = -1; // Used to denote which PlayField to be placed into
									// Leave -1 if it should be automatically determined based on mustPress and placed into either bf or dad's based on that.
									// Note that holds automatically have this set to their parent's fieldIndex
	public var field:PlayField; // same as fieldIndex but lets you set the field directly incase you wanna do that i  guess
	public var finalized:Bool = false; // If true, note has been finalized and is ready to spawn; if false, finalization is deferred to playfield spawn
	private function set_scrollSpeed(value:Float):Float {
		scrollSpeed = value;
		return value;
	}

	public var copyVerts:Bool = true;
	public var typeOffsetAngle:Float = 0;
	public var expectedData:Int = -1;
	#if PE_MOD_COMPATIBILITY
	@:isVar
	public var multAlpha(get, set):Float;
	function get_multAlpha()return alphaMod;
	function set_multAlpha(v:Float)return alphaMod = v;

	// Angle is controlled by verts in the modchart system
	@:isVar public var copyAngle(get, set):Bool;
	function get_copyAngle()return copyVerts;
	function set_copyAngle(val:Bool)return copyVerts = val;
	#end

	public var istail:Bool = false;

	//AI Stuff
	public var AIStrumTime:Float = 0;
	public var AIMiss:Bool = false;

	public var hitsoundDisabled:Bool = false;
	public var hitsoundChartEditor:Bool = true;
	/**
	 * Forces the hitsound to be played even if the user's hitsound volume is set to 0
	**/
	public var hitsoundForce:Bool = false;
	public var hitsoundVolume(get, default):Float = 1.0;
	function get_hitsoundVolume():Float {
		if(ClientPrefs.data.hitsoundVolume > 0)
			return ClientPrefs.data.hitsoundVolume;
		return hitsoundForce ? hitsoundVolume : 0.0;
	}
	public var hitsound:String = 'hitsound';
	public var doRGBShader:Bool = true;

	public var noteSplashTexture:String = "";

	public static var hardAlpha:Float = 1; // For hard mode

	private function set_multSpeed(value:Float):Float {
		resizeByRatio(value / multSpeed);
		multSpeed = value;
		//trace('fuck cock');
		return value;
	}

	public function resizeByRatio(ratio:Float) //haha funny twitter shit
	{
		if(isSustainNote && animation.curAnim != null && !animation.curAnim.name.endsWith('tail'))
		{
			scale.y *= ratio;
			updateHitbox();
		}
	}

	private function set_texture(value:String):String {
		// If this is an AP check note, override the texture
		if(isCheck && value != 'noteSkins/ap_assets/AP_NOTE') {
			value = 'noteSkins/ap_assets/AP_NOTE';
			this.shader = null; // no shader please :D
		}

		if(texture != value) reloadNote(value);

		texture = value;
		return value;
	}

	public function defaultRGB()
	{
		var arr:Array<FlxColor> = ClientPrefs.data.arrowRGBExtra[Note.keysShit.get(PlayState.mania).get('pixelAnimIndex')[noteData]];
		if(PlayState.isPixelStage) arr = ClientPrefs.data.arrowRGBPixelExtra[Note.keysShit.get(PlayState.mania).get('pixelAnimIndex')[noteData]];

		if (arr != null && noteData > -1 && noteData <= PlayState.mania)
		{
			// Store temporarily if in preload mode, otherwise set directly
			if (isInPreloadMode && tempRGBColors != null) {
				tempRGBColors.r = arr[0];
				tempRGBColors.g = arr[1];
				tempRGBColors.b = arr[2];
			} else if (rgbShader != null) {
				rgbShader.r = arr[0];
				rgbShader.g = arr[1];
				rgbShader.b = arr[2];
			}
			#if ARCHIPELAGO_ALLOWED
			if (this is archipelago.APNote)
			{
				trace("AP Color.");
				shader = null;
			}
			#end
		}
		else
		{
			// Store temporarily if in preload mode, otherwise set directly
			if (isInPreloadMode && tempRGBColors != null) {
				tempRGBColors.r = 0xFFFF0000;
				tempRGBColors.g = 0xFF00FF00;
				tempRGBColors.b = 0xFF0000FF;
			} else if (rgbShader != null) {
				rgbShader.r = 0xFFFF0000;
				rgbShader.g = 0xFF00FF00;
				rgbShader.b = 0xFF0000FF;
			}
		}
	}

	private function set_noteType(value:String):String {
		noteSplashData.texture = PlayState.SONG != null ? PlayState.SONG.splashSkin : 'noteSplashes/noteSplashes';
		defaultRGB();

		if(noteData > -1 && noteType != value) {
			switch(value) {
				case 'Hurt Note':
					ignoreNote = mustPress;

					// note colors
				// Store temporarily if in preload mode, otherwise set directly
				if (isInPreloadMode && tempRGBColors != null) {
					tempRGBColors.r = 0xFF101010;
					tempRGBColors.g = 0xFFFF0000;
					tempRGBColors.b = 0xFF990022;
				} else if (rgbShader != null) {
					rgbShader.r = 0xFF101010;
					rgbShader.g = 0xFFFF0000;
					rgbShader.b = 0xFF990022;
				}
					noteSplashData.texture = 'noteSplashes/noteSplashes-electric';

					// gameplay data
					lowPriority = true;
					missHealth = isSustainNote ? 0.25 : 0.1;
					hitCausesMiss = true;
					hitsound = 'cancelMenu';
					hitsoundChartEditor = false;
				case 'Kill Note':
					ignoreNote = mustPress;
					reloadNote('noteSkins/mechanicsmod/KILLNOTE_assets');
					noteSplashData.texture = 'noteSplashes/HURTnoteSplashes';
					rgbShader.enabled = false;
					missHealth = FlxMath.MAX_VALUE_FLOAT;
					lowPriority = true;
					hitCausesMiss = true;
				case 'Burst Note':
					ignoreNote = mustPress;
					reloadNote('noteSkins/mechanicsmod/BURSTNOTE_assets');
					noteSplashData.disabled = true;
					rgbShader.enabled = false;
					if (isSustainNote)
					{
						missHealth = 0.0475 / 2;
					}
					else
					{
						missHealth = 0.0475;
					}
					hitCausesMiss = true;
					lowPriority = true;
				case 'Sleep Note':
					ignoreNote = mustPress;
					reloadNote('noteSkins/mechanicsmod/SLEEPYNOTE_assets');
					noteSplashData.disabled = true;
					rgbShader.enabled = false;
					if (isSustainNote)
					{
						missHealth = 0.0475 / 2;
					}
					else
					{
						missHealth = 0.0475;
					}
					hitCausesMiss = true;
					lowPriority = true;
				case 'Restore Note':
					reloadNote('noteSkins/mechanicsmod/RESTORENOTE_assets');
					if (isSustainNote)
					{
						missHealth = 0.0475 / 2;
					}
					else
					{
						missHealth = 0.0475;
					}
					rgbShader.enabled = false;
				case 'Fake Note':
					ignoreNote = mustPress;
					reloadNote('noteSkins/mechanicsmod/FAKENOTE_assets');
					noteSplashData.texture = 'HURTnoteSplashes';
					rgbShader.enabled = false;
					if (isSustainNote)
					{
						missHealth = 0.0475 / 2;
					}
					else
					{
						missHealth = 0.0475;
					}
					hitCausesMiss = true;
				case 'Swap Note':
					reloadNote('noteSkins/mechanicsmod/SWAPNOTE_assets');
					rgbShader.enabled = false;
					if (isSustainNote)
					{
						missHealth = 0.0475 / 2;
					}
					else
					{
						missHealth = 0.0475;
					}
				case 'Alt Animation':
					animSuffix = '-alt';
				case 'No Animation':
					noAnimation = true;
					noMissAnimation = true;
				case 'GF Sing':
					gfNote = true;
				case 'EX Note':
					exNote = true;
				case 'Botplay Note':
					botNote = true;
					hitsoundChartEditor = false;
				case "Throat Note":
					reloadNote('noteSkins/mechanicsmod/THROATNOTE_assets');
					ignoreNote = mustPress;
					hitCausesMiss = true;
					missHealth = 0.0475;
				case 'sakura-joint':
					//animSuffix = '-both';
				case 'sakura-bf1':
					animSuffix = '-bf';
				case 'sakura-bf2':
					animSuffix = '-bfA';
			}
			if (value != null && value.length > 1) NoteTypesConfig.applyNoteTypeData(this, value);
			if (hitsound != 'hitsound' && hitsoundVolume > 0) Paths.sound(hitsound); //precache new sound for being idiot-proof
			noteType = value;
		}
		return value;
	}

	override function toString()
	{
		return '(column: $column | noteType: $noteType | strumTime: $strumTime | visible: $visible)';
	}

	override function set_alpha(Alpha:Float):Float {
		multAlpha = Alpha;
		// trace('set alpha: ' + Alpha);
		return super.set_alpha(Alpha * hardAlpha);
	}
	public var isNotePool:Bool = false;
	/**
	 * Reference to the note pool that created this note (if any)
	 */
	public var notePool:objects.NotePool = null;
	public function new(?strumTime:Float, ?noteData:Int, ?prevNote:Note, ?sustainNote:Bool = false, ?inEditor:Bool = false, ?createdFrom:Dynamic = null, ?inNotePool:Bool = false)
	{
		super();
		isNotePool = inNotePool;

		if (noteSplashTexture != '') noteSplashData.texture = noteSplashTexture;

		animation = new PsychAnimationController(this);

		antialiasing = ClientPrefs.data.antialiasing;
		if(createdFrom == null) createdFrom = PlayState.instance;

		if (prevNote == null)
			prevNote = this;

		this.objType = NOTE;
		this.column = noteData;

		this.prevNote = prevNote;
		isSustainNote = sustainNote;
		this.inEditor = inEditor;
		this.moves = false;
		this.beat = Conductor.getBeat(strumTime);

		if (inNotePool) return;

		// Early return during preload mode - finish initialization later
		if (ClientPrefs.data.preloadSong && !inEditor) {
			// Store basic data for later completion
			this.strumTime = strumTime;
			this.noteData = noteData;
			isInPreloadMode = true;
			// Initialize temp RGB colors storage
			tempRGBColors = {r: FlxColor.WHITE, g: FlxColor.WHITE, b: FlxColor.WHITE};
			// Store RGB-related data temporarily
			if (noteData > -1) {
				tempRGBData = {
					noteData: noteData,
					disableRGB: PlayState.SONG != null && PlayState.SONG.disableNoteRGB && !isCheck,
					isPixelStage: PlayState.isPixelStage,
					postfix: getNoteSkinPostfix().toLowerCase()
				};
			}
			return;
		}

		// Add a function to complete this stuff if we decide to return for another reason later

		if (isSustainNote && prevNote != null) {
			parentNote = prevNote;
			while (parentNote.parentNote != null)
				parentNote = parentNote.parentNote;
			parentNote.childrenNotes.push(this);
		} else if (!isSustainNote)
			parentNote = null;

		baseAlpha = 1;

		x += (ClientPrefs.data.middleScroll ? PlayState.STRUM_X_MIDDLESCROLL : PlayState.STRUM_X) + 50;
		// MAKE SURE ITS DEFINITELY OFF SCREEN?
		y -= 2000;
		this.strumTime = strumTime;
		if(!inEditor) {
			this.strumTime += ClientPrefs.data.noteOffset;
			visualTime = PlayState.getNoteInitialTime(this.strumTime);
		}

		this.noteData = noteData;

		if(noteData > -1)
		{
			rgbShader = new RGBShaderReference(this, initializeGlobalRGBShader(noteData));
			if(PlayState.SONG != null && PlayState.SONG.disableNoteRGB && !isCheck) rgbShader.enabled = false;
			texture = '';

			if (PlayState.isPixelStage || getNoteSkinPostfix().toLowerCase() == '-retribution')
				rgbShader.enabled = false;

			if(!isSustainNote && noteData > -1 && noteData < Note.maxManiaUI_integer) { //Doing this 'if' check to fix the warnings on Senpai songs
				var animToPlay:String = '';
				animToPlay = Note.keysShit.get(PlayState.mania).get('letters')[noteData];
				if (hasAnimation(animToPlay))
					animation.play(animToPlay);
				else
				{
					animToPlay = colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]];
					animation.play(animToPlay + 'Scroll');
				}
			}

			x += swagWidth * (noteData % Note.ammo[PlayState.mania]);
		}

		// trace(prevNote);

		if(prevNote != null)
			prevNote.nextNote = this;

		if (isSustainNote)
		{
			alphaLimit = 0.6;
		}

		if (isSustainNote && prevNote != null)
		{
			alpha = 0.6;
			multAlpha = 0.6;
			hitsoundDisabled = true;
			if(ClientPrefs.data.downScroll) flipY = true;

			istail = true;

			//offsetY += height / 2;

			var animToPlay:String = '';
			animToPlay = Note.keysShit.get(PlayState.mania).get('letters')[noteData] + ' tail';
			if (!hasAnimation(animToPlay))
			{
				animToPlay = colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + 'holdend';
			}
			animation.play(animToPlay);

			//scale.y = 0.7;
			updateHitbox();
    	centerOffsets();

			//offsetY += height;

			//if (PlayState.isPixelStage)
				//offsetX += 30;

			if (prevNote != null && prevNote.isSustainNote)
			{
				var animToPlay2:String = '';
				animToPlay2 = Note.keysShit.get(PlayState.mania).get('letters')[noteData] + ' hold';
				if (!hasAnimation(animToPlay2))
				{
					animToPlay2 = colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + 'hold';
				}
				prevNote.animation.play(animToPlay2);

				prevNote.scale.y *= Conductor.stepCrochet / 100 * 1.05;
				if(createdFrom != null && createdFrom.songSpeed != null) prevNote.scale.y *= createdFrom.songSpeed;

				if(PlayState.isPixelStage) {
					prevNote.scale.y *= 1.19;
					prevNote.scale.y *= (6 / height); //Auto adjust note size
				}
				prevNote.updateHitbox();
				prevNote.centerOffsets();

				// offsetY += height / 2;
				// prevNote.setGraphicSize();
			}

			if(PlayState.isPixelStage)
			{
				scale.y *= PlayState.daPixelZoom;
				updateHitbox();
				centerOffsets();
			}
			earlyHitMult = 0;
		}
		else if(!isSustainNote)
		{
			centerOffsets();
			centerOrigin();
			centerOffsets();
		}
		//x += offsetX;
		finalized = true;
	}

	/**
	 * Complete note initialization that was skipped during preload mode
	 */
	public function finishNoteInitialization():Void {
		// Skip if already fully initialized or in editor
		if (inEditor || !ClientPrefs.data.preloadSong) return;

		// Complete the initialization that was skipped during preload
		if (isSustainNote && prevNote != null) {
			parentNote = prevNote;
			while (parentNote.parentNote != null)
				parentNote = parentNote.parentNote;
			parentNote.childrenNotes.push(this);
		} else if (!isSustainNote)
			parentNote = null;

		baseAlpha = 1;

		x += (ClientPrefs.data.middleScroll ? PlayState.STRUM_X_MIDDLESCROLL : PlayState.STRUM_X) + 50;
		// MAKE SURE ITS DEFINITELY OFF SCREEN?
		y -= 2000;

		if(!inEditor) {
			this.strumTime += ClientPrefs.data.noteOffset;
			visualTime = PlayState.getNoteInitialTime(this.strumTime);
		}

		if(noteData > -1)
		{
			// Apply RGB data from temporary storage if available
			if (tempRGBData != null) {
				rgbShader = new RGBShaderReference(this, initializeGlobalRGBShader(tempRGBData.noteData));
				if(tempRGBData.disableRGB) rgbShader.enabled = false;
				texture = '';

				if (tempRGBData.isPixelStage || tempRGBData.postfix == '-retribution')
					rgbShader.enabled = false;

				// Apply stored RGB color values
				if (tempRGBColors != null && rgbShader != null) {
					rgbShader.r = tempRGBColors.r;
					rgbShader.g = tempRGBColors.g;
					rgbShader.b = tempRGBColors.b;
					tempRGBColors = null;
				}

				// Clear temporary data
				tempRGBData = null;
				isInPreloadMode = false;
			} else {
				// Fallback initialization if no temp data
				rgbShader = new RGBShaderReference(this, initializeGlobalRGBShader(noteData));
				if(PlayState.SONG != null && PlayState.SONG.disableNoteRGB && !isCheck) rgbShader.enabled = false;
				texture = '';

				if (PlayState.isPixelStage || getNoteSkinPostfix().toLowerCase() == '-retribution')
					rgbShader.enabled = false;
			}

			if(!isSustainNote && noteData > -1 && noteData < Note.maxManiaUI_integer) { //Doing this 'if' check to fix the warnings on Senpai songs
				var animToPlay:String = '';
				animToPlay = Note.keysShit.get(PlayState.mania).get('letters')[noteData];
				if (hasAnimation(animToPlay))
					animation.play(animToPlay);
				else
				{
					animToPlay = colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]];
					animation.play(animToPlay + 'Scroll');
				}
			}

			x += swagWidth * (noteData % Note.ammo[PlayState.mania]);
		}

		// trace(prevNote);

		if(prevNote != null)
			prevNote.nextNote = this;

		if (isSustainNote)
		{
			alphaLimit = 0.6;
		}

		if (isSustainNote && prevNote != null)
		{
			alpha = 0.6;
			multAlpha = 0.6;
			hitsoundDisabled = true;
			if(ClientPrefs.data.downScroll) flipY = true;

			istail = true;

			//offsetY += height / 2;

			var animToPlay:String = '';
			animToPlay = Note.keysShit.get(PlayState.mania).get('letters')[noteData] + ' tail';
			if (!hasAnimation(animToPlay))
			{
				animToPlay = colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + 'holdend';
			}
			animation.play(animToPlay);

			//scale.y = 0.7;
			updateHitbox();
			centerOffsets();

			//offsetY += height;

			//if (PlayState.isPixelStage)
				//offsetX += 30;

			if (prevNote != null && prevNote.isSustainNote)
			{
				var animToPlay2:String = '';
				animToPlay2 = Note.keysShit.get(PlayState.mania).get('letters')[noteData] + ' hold';
				if (!hasAnimation(animToPlay2))
				{
					animToPlay2 = colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + 'hold';
				}
				prevNote.animation.play(animToPlay2);

				prevNote.scale.y *= Conductor.stepCrochet / 100 * 1.05;
				if(PlayState.instance != null && PlayState.instance.songSpeed.isReal()) prevNote.scale.y *= PlayState.instance.songSpeed;

				if(PlayState.isPixelStage) {
					prevNote.scale.y *= 1.19;
					prevNote.scale.y *= (6 / height); //Auto adjust note size
				}
				prevNote.updateHitbox();
				prevNote.centerOffsets();

				// offsetY += height / 2;
				// prevNote.setGraphicSize();
			}

			if(PlayState.isPixelStage)
			{
				scale.y *= PlayState.daPixelZoom;
				updateHitbox();
				centerOffsets();
			}
			earlyHitMult = 0;
		}
		else if(!isSustainNote)
		{
			centerOffsets();
			centerOrigin();
			centerOffsets();
		}
		//x += offsetX;
		finalized = true;

	}

	public static function initializeGlobalRGBShader(noteData:Int)
	{
		if(globalRgbShaders[noteData] == null)
		{
			var newRGB:RGBPalette = new RGBPalette();
			var arr:Array<FlxColor> = (!PlayState.isPixelStage) ? ClientPrefs.data.arrowRGBExtra[noteData] : ClientPrefs.data.arrowRGBPixelExtra[noteData];
			//trace(arr.length);
			if (noteData > -1 && noteData <= arr.length)
			{
				newRGB.r = arr[0];
				newRGB.g = arr[1];
				newRGB.b = arr[2];
			}
			else
			{
				newRGB.r = 0xFFFF0000;
				newRGB.g = 0xFF00FF00;
				newRGB.b = 0xFF0000FF;
			}

			globalRgbShaders[noteData] = newRGB;
		}
		return globalRgbShaders[noteData];
	}

	public var publicTexture:String = '';
	public var publicTextureSus:String = '';
	var _lastNoteOffX:Float = 0;
	static var _lastValidChecked:String; //optimization
	public var originalHeight:Float = 6;
	public var correctionOffset:Float = 0; //dont mess with this
	public function reloadNote(texture:String = '', postfix:String = '') {
		if(texture == null) texture = '';
		if(postfix == null) postfix = '';

		var skin:String = texture + postfix;
		if(texture.length < 1)
		{
			skin = PlayState.SONG != null ? PlayState.SONG.arrowSkin : null;
			if (skin == null || skin.length < 1)
				skin = "noteSkins/NOTE_assets" + postfix;
		}

		var animName:String = null;
		if(animation != null && animation.curAnim != null) {
			animName = animation.curAnim.name;
		}

		var skinPixel:String = skin;
		var lastScaleY:Float = (scale != null ? scale.y : 0.7);
		var skinPostfix:String = getNoteSkinPostfix();
		var customSkin:String = skin + skinPostfix;
		var path:String = PlayState.isPixelStage ? 'pixelUI/' : '';
		if(skinPostfix != '' && (customSkin == _lastValidChecked || Paths.fileExists('images/' + path + customSkin + '.png', IMAGE)))
		{
			skin = customSkin;
			_lastValidChecked = customSkin;
		}
		else skinPostfix = '';

		defaultWidth = 157;
		defaultHeight = 154;

		if(PlayState.isPixelStage) {
			switch (noteType)
			{
				case 'Mine Note':
					loadGraphic(Paths.image("streamervschat/pixelUI/minenote"), false);
				case 'Warning Note':
					loadGraphic(Paths.image("streamervschat/pixelUI/warningnote"), false);
				case 'Heal Note':
					loadGraphic(Paths.image("streamervschat/pixelUI/healnote"), false);
				case 'Ice Note':
					loadGraphic(Paths.image("streamervschat/pixelUI/icenote"), false);
				case 'Fake Heal Note':
					loadGraphic(Paths.image("streamervschat/pixelUI/fakehealnote"), false);
				default:
					publicTexture = 'pixelUI/' + skinPixel + skinPostfix;
					publicTextureSus = 'pixelUI/' + skinPixel + 'ENDS' + skinPostfix;
					if(isSustainNote) {
						var graphic = Paths.image('pixelUI/' + skinPixel + 'ENDS' + skinPostfix);
						loadGraphic(graphic, true, Math.floor(graphic.width / pixelNotesDivisionValue[graphic.width == 126 ? 1 : 0]), Math.floor(graphic.height / 2));
						originalHeight = graphic.height / 2;
					} else {
						var graphic = Paths.image('pixelUI/' + skinPixel + skinPostfix);
						loadGraphic(graphic, true, Math.floor(graphic.width / pixelNotesDivisionValue[graphic.width == 306 ? 1 : 0]), Math.floor(graphic.height / 5));
					}
					setGraphicSize(Std.int(width * PlayState.daPixelZoom * pixelScales[PlayState.mania]));
					loadPixelNoteAnims();
					antialiasing = false;
			}
		} else {
			switch (noteType)
			{
				case 'Mine Note':
					loadGraphic(Paths.image("streamervschat/minenote"), false);
				case 'Warning Note':
					loadGraphic(Paths.image("streamervschat/warningnote"), false);
				case 'Heal Note':
					loadGraphic(Paths.image("streamervschat/healnote"), false);
				case 'Ice Note':
					loadGraphic(Paths.image("streamervschat/icenote"), false);
				case 'Fake Heal Note':
					loadGraphic(Paths.image("streamervschat/fakehealnote"), false);
				default:
					frames = Paths.getSparrowAtlas(skin);
					loadNoteAnims();
					if (!isSustainNote) {
						centerOffsets();
						centerOrigin();
					}
			}
		}

		if(isSustainNote) {
			scale.y = lastScaleY;
		}
		if (inEditor)
			setGraphicSize(ChartingState.GRID_SIZE, ChartingState.GRID_SIZE);

		defScale.copyFrom(scale);
		updateHitbox();

		if(animName != null)
			animation.play(animName, true);
	}

	public static function getNoteSkinPostfix()
	{
		var skin:String = '';
		if(ClientPrefs.data.noteSkin != ClientPrefs.defaultData.noteSkin)
			skin = '-' + ClientPrefs.data.noteSkin.trim().toLowerCase().replace(' ', '_');
		return skin;
	}

	function loadNoteAnims() {
		/*for (i in 0...gfxLetter.length)
		{
			attemptToAddAnimationByPrefix(gfxLetter[i], colArray[Note.keysShit.get(PlayState.mania).get('colArray')[i]] + '0');
			attemptToAddAnimationByPrefix(gfxLetter[i], colArray[Note.keysShit.get(PlayState.mania).get('colArray')[i]] + '0');
			attemptToAddAnimationByPrefix(gfxLetter[i], gfxLetter[i] + '0');

			if (isSustainNote)
			{
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', 'pruple end hold');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', colArray[Note.keysShit.get(PlayState.mania).get('colArray')[i]] + ' hold end');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' hold', colArray[Note.keysShit.get(PlayState.mania).get('colArray')[i]] + ' hold piece');

				attemptToAddAnimationByPrefix(gfxLetter[i] + ' hold', gfxLetter[i] + ' hold');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', gfxLetter[i] + ' tail');
			}
		}*/

		for (i in 0...gfxLetter.length)
		{
			attemptToAddAnimationByPrefix(gfxLetter[i], gfxLetter[i] + '0');
			attemptToAddAnimationByPrefix(gfxLetter[i], colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + '0');
			attemptToAddAnimationByPrefix(gfxLetter[i], colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + '0');

			if (isSustainNote)
			{
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + ' hold end');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' hold', colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + ' hold piece');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' hold', gfxLetter[i] + ' hold');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', gfxLetter[i] + ' tail');

				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', 'pruple end hold');
				attemptToAddAnimationByPrefix(gfxLetter[i] + ' tail', colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + ' hold end');

				attemptToAddAnimationByPrefix(gfxLetter[i] + ' hold', colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + ' hold piece');
			}
		}

		if (isSustainNote)
			setGraphicSize(Std.int(width * scales[PlayState.mania]), Std.int(defaultHeight * scales[PlayState.mania] * 5));
		else
			setGraphicSize(Std.int(width * scales[PlayState.mania]));
		updateHitbox();
	}

	function loadPixelNoteAnims() {
		// Optimize Anim Loading.
		var colorIndex:Int = Note.keysShit.get(PlayState.mania).get('pixelAnimIndex')[noteData];
		var animName:String = gfxLetter[noteData];

		if (animName != null) {
			var graphic = Paths.image(publicTexture);
			animation.add(animName, [colorIndex + pixelNotesDivisionValue[graphic.width == 306 ? 1 : 0]]);
			if (isSustainNote)
			{
				animation.add(animName + ' hold', [colorIndex]);
				animation.add(animName + ' tail', [colorIndex + (pixelNotesDivisionValue[graphic.width == 126 ? 1 : 0] * 2)]);
			}
		}
	}

	function attemptToAddAnimationByPrefix(name:String, prefix:String, framerate:Float = 24, doLoop:Bool = true)
	{
		try {
			var animFrames = [];
			@:privateAccess
			animation.findByPrefix(animFrames, prefix); // adds valid frames to animFrames
			if(animFrames.length < 1) return;

			animation.addByPrefix(name, prefix, framerate, doLoop);
		}
		catch(e){
			//trace("Anim was null!: " + prefix);
		}
	}

	override function draw()
	{
		if (tooLate && !inEditor)
		{
			if (alpha > 0.3)
				alpha = 0.3;
		}

		super.draw();

		// Draw UNO card elements if this is a UNO note
		if (extraData != null && extraData.exists("unoCard")) {
			drawUnoCard();
		}
	}

	/**
	 * Finalizes the note by completing initialization.
	 * When "Finalize at Birth" is enabled during preload, this defers expensive
	 * initialization until the note actually spawns into the playfield.
	 */
	public function finalize():Void
	{
		if (!finalized) {
			finishNoteInitialization();
			finalized = true;
		}
	}

	override function update(elapsed:Float)
	{
		try {
			if (!inEditor) {
				if (field != null && alpha > field.strumNotes[column].alpha && strumTime > 1500) //Since the first couple of notes tend to just dissapear here's a hopeful fix for that
					alpha = field.strumNotes[column].alpha;
			}
		} catch(e) {}

		super.update(elapsed);

		if (hitByOpponent) wasGoodHit = true;

		var diff = (strumTime - Conductor.songPosition);
		if (diff < -Conductor.safeZoneOffset && !wasGoodHit) {
			tooLate = true;
		}

		if (tooLate && !inEditor)
		{
			if (alpha > 0.3)
				alpha = 0.3;
		}

		// Handle UNO +2/+4 note animations
		updateUnoAnimations(elapsed);
	}

	override public function destroy()
	{
		if (isNotePool && notePool != null) {
			// Return to pool instead of destroying
			notePool.returnNote(this);
			return;
		}
		super.destroy();
		_lastValidChecked = '';
	}

	/**
	 * Force destroy this note, removing it from the pool if necessary
	 */
	public function forceDestroy():Void
	{
		// Temporarily disable pool protection
		var wasPooled = isNotePool;
		isNotePool = false;

		// Actually destroy the note
		super.destroy();
		_lastValidChecked = '';

		// Check for note in the pool and remove it if found
		if (wasPooled && notePool != null) {
			notePool.removeNote(this);
		}

		// Clear pool reference

		notePool = null;
	}

	public function followStrumNote(myStrum:StrumNote, fakeCrochet:Float, songSpeed:Float = 1)
	{
		var strumX:Float = myStrum.x;
		var strumY:Float = myStrum.y;
		var strumAngle:Float = myStrum.angle;
		var strumAlpha:Float = myStrum.alpha;
		var strumDirection:Float = myStrum.direction;

		distance = (0.45 * (Conductor.songPosition - strumTime) * songSpeed * multSpeed);
		if (!myStrum.downScroll) distance *= -1;

		var angleDir = strumDirection * Math.PI / 180;
		if (copyAngle)
			angle = strumDirection - 90 + strumAngle + offsetAngle;

		if(copyAlpha)
			alpha = strumAlpha * multAlpha;

		if(copyX)
			x = strumX + offsetX + Math.cos(angleDir) * distance;

		if(copyY)
		{
			y = strumY + offsetY + correctionOffset + Math.sin(angleDir) * distance;
			if(myStrum.downScroll && isSustainNote)
			{
				if(PlayState.isPixelStage)
				{
					y -= PlayState.daPixelZoom * 9.5;
				}
				y -= (frameHeight * scale.y) - (Note.swagWidth / 2);
			}
		}
	}

	public function clipToStrumNote(myStrum:StrumNote)
	{
		var center:Float = myStrum.y + offsetY + Note.swagWidth / 2;
		if((mustPress || !ignoreNote) && (wasGoodHit || (prevNote.wasGoodHit && !canBeHit)))
		{
			var swagRect:FlxRect = clipRect;
			if(swagRect == null) swagRect = new FlxRect(0, 0, frameWidth, frameHeight);

			if (myStrum.downScroll)
			{
				if(y - offset.y * scale.y + height >= center)
				{
					swagRect.width = frameWidth;
					swagRect.height = (center - y) / scale.y;
					swagRect.y = frameHeight - swagRect.height;
				}
			}
			else if (y + offset.y * scale.y <= center)
			{
				swagRect.y = (center - y) / scale.y;
				swagRect.width = width / scale.x;
				swagRect.height = (height / scale.y) - swagRect.y;
			}
			clipRect = swagRect;
		}
	}

	@:noCompletion
	override function set_clipRect(rect:FlxRect):FlxRect
	{
		clipRect = rect;

		if (frames != null)
			frame = frames.frames[animation.frameIndex];

		return rect;
	}

	/**
	 * Handle UNO +2/+4 note animations
	 */
	private function updateUnoAnimations(elapsed:Float):Void {
		if (extraData == null) return;

		var isSecondaryPlusCard:Bool = cast extraData.get("isSecondaryPlusCard");
		if (isSecondaryPlusCard != true) return;

		var originalX:Dynamic = extraData.get("originalX");
		var targetColumn:Dynamic = extraData.get("targetColumn");
		var hasStartedTween:Bool = cast extraData.get("hasStartedTween");

		if (originalX != null && targetColumn != null && field != null) {
			var originalXFloat:Float = cast originalX;
			var targetColumnInt:Int = cast targetColumn;

			// Check if close enough to strum to start animation
			var strumY = field.strumNotes[0].y;
			var distanceToStrum = Math.abs(y - strumY);

			// Start tween when note is close to strum (within 200 pixels)
			if (distanceToStrum < 200 && hasStartedTween != true) {
				extraData.set("hasStartedTween", true);

				// Calculate target X position
				var targetX = field.strumNotes[targetColumnInt].x;

				// Start from original position
				x = originalXFloat;

				// Create tween to target position
				flixel.tweens.FlxTween.tween(this, {x: targetX, angle: 360}, 0.5, {
					ease: flixel.tweens.FlxEase.circOut,
					onComplete: function(tween:flixel.tweens.FlxTween) {
						angle = 0; // Reset angle after tween
					}
				});
			}
		}
	}

	/**
	 * Draw UNO card visual elements on the note
	 */
	private function drawUnoCard():Void {
		if (extraData == null) return;

		var displayText:String = cast extraData.get("unoDisplayText");
		var colorHexDynamic:Dynamic = extraData.get("unoColorHex");
		var isWrongCard:Bool = cast extraData.get("isWrongCard");
		var isSkipCard:Bool = cast extraData.get("isSkipCard");
		var isPlusCard:Bool = cast extraData.get("isPlusCard");
		var unoType:String = cast extraData.get("unoType");

		if (displayText == null) return;

		// Only draw on visible notes
		if (!visible || alpha <= 0) return;

		// Set note's RGB color based on UNO card color (affects the note's red channel)
		if (colorHexDynamic != null && rgbShader != null) {
			var colorHex:Int = cast colorHexDynamic;
			// Store temporarily if in preload mode, otherwise set directly
			if (isInPreloadMode && tempRGBColors != null) {
				tempRGBColors.r = colorHex;
			} else {
				rgbShader.r = colorHex;
			}
		}

        // Create text display for the UNO card (always white unless wild)
        var cardText = new flixel.text.FlxText(x + width * 0.25, y + height * 0.25, width * 0.5, displayText);
        cardText.setFormat(null, 16, 0xFFFFFFFF, CENTER);
        cardText.setBorderStyle(OUTLINE, 0xFF000000, 2);        // Special handling for different card types
        if (isSkipCard == true) {
            // Draw skip icon manually instead of emoji
            drawSkipIcon();
        } else if (unoType == "Reverse") {
            // Draw reverse arrows manually
            drawReverseIcon();
        } else if (unoType == "Wild" || unoType == "WildDrawFour") {
            // Wild cards get colorful text
            cardText.color = colorHexDynamic != null ? cast(colorHexDynamic, Int) : 0xFFFFFFFF;
            // Draw the text for wild cards
            cardText.alpha = alpha;
            cardText.draw();
        } else {
            // All other cards (numbers, +2) have white text
            cardText.color = 0xFFFFFFFF;

            // Special styling for wrong cards
            if (isWrongCard == true) {
                // Wrong cards get red outline instead of red text
                cardText.setBorderStyle(OUTLINE, 0xFFFF0000, 3);
            }

            if (isPlusCard == true) {
                // Add yellow glow effect for plus cards
                cardText.setBorderStyle(OUTLINE, 0xFFFFFF00, 3);
            }

            // Draw the text for regular cards
            cardText.alpha = alpha;
            cardText.draw();
        }

        if (cardText != null) {
            cardText.destroy();
        }
    }

	/**
	 * Manually draw a skip icon (circle with diagonal line)
	 */
	private function drawSkipIcon():Void {
		// Create a sprite for the skip icon
		var skipGraphic = new flixel.FlxSprite(x + width * 0.2, y + height * 0.2);
		skipGraphic.makeGraphic(Std.int(width * 0.6), Std.int(height * 0.6), 0x00000000);

		// Get the graphics context
		var graphics = skipGraphic.pixels;
		if (graphics != null) {
			graphics.lock();

			// Draw circle outline
			var centerX = Std.int(skipGraphic.width * 0.5);
			var centerY = Std.int(skipGraphic.height * 0.5);
			var radius = Std.int(Math.min(skipGraphic.width, skipGraphic.height) * 0.4);

			// Draw circle (simplified approach)
			for (angle in 0...360) {
				var radians = angle * Math.PI / 180;
				var px = centerX + Std.int(radius * Math.cos(radians));
				var py = centerY + Std.int(radius * Math.sin(radians));

				if (px >= 0 && px < skipGraphic.width && py >= 0 && py < skipGraphic.height) {
					graphics.setPixel32(px, py, 0xFFFFFFFF);
				}
			}

			// Draw diagonal line through circle
			var lineThickness = 3;
			for (i in 0...lineThickness) {
				for (j in 0...Std.int(skipGraphic.width)) {
					var lineY = centerY - (j - centerX) + i - 1;
					if (lineY >= 0 && lineY < skipGraphic.height && j >= 0 && j < Std.int(skipGraphic.width)) {
						graphics.setPixel32(j, Std.int(lineY), 0xFFFFFFFF);
					}
				}
			}

			graphics.unlock();
			skipGraphic.alpha = alpha;
			skipGraphic.draw();
		}

		skipGraphic.destroy();
	}

	/**
	 * Manually draw a reverse icon (circular arrows)
	 */
	private function drawReverseIcon():Void {
		// Create a sprite for the reverse icon
		var reverseGraphic = new flixel.FlxSprite(x + width * 0.2, y + height * 0.2);
		reverseGraphic.makeGraphic(Std.int(width * 0.6), Std.int(height * 0.6), 0x00000000);

		// Get the graphics context
		var graphics = reverseGraphic.pixels;
		if (graphics != null) {
			graphics.lock();

			var centerX = Std.int(reverseGraphic.width * 0.5);
			var centerY = Std.int(reverseGraphic.height * 0.5);
			var radius = Std.int(Math.min(reverseGraphic.width, reverseGraphic.height) * 0.3);

			// Draw two curved arrows (simplified as circular arcs)
			for (angle in 45...135) { // Top arc
				var radians = angle * Math.PI / 180;
				var px = centerX + Std.int(radius * Math.cos(radians));
				var py = centerY + Std.int(radius * Math.sin(radians)) - 5;

				if (px >= 0 && px < reverseGraphic.width && py >= 0 && py < reverseGraphic.height) {
					graphics.setPixel32(px, py, 0xFFFFFFFF);
				}
			}

			for (angle in 225...315) { // Bottom arc
				var radians = angle * Math.PI / 180;
				var px = centerX + Std.int(radius * Math.cos(radians));
				var py = centerY + Std.int(radius * Math.sin(radians)) + 5;

				if (px >= 0 && px < reverseGraphic.width && py >= 0 && py < reverseGraphic.height) {
					graphics.setPixel32(px, py, 0xFFFFFFFF);
				}
			}

			// Add arrow heads (simplified as small lines)
			// Top arrow head
			for (i in 0...5) {
				var px = centerX - radius + i;
				var py = centerY - 8 + i;
				if (px >= 0 && px < reverseGraphic.width && py >= 0 && py < reverseGraphic.height) {
					graphics.setPixel32(px, py, 0xFFFFFFFF);
				}
			}

			// Bottom arrow head
			for (i in 0...5) {
				var px = centerX + radius - i;
				var py = centerY + 8 - i;
				if (px >= 0 && px < reverseGraphic.width && py >= 0 && py < reverseGraphic.height) {
					graphics.setPixel32(px, py, 0xFFFFFFFF);
				}
			}

			graphics.unlock();
			reverseGraphic.alpha = alpha;
			reverseGraphic.draw();
		}

		reverseGraphic.destroy();
	}
}
