package objects;

import objects.Note;
import objects.StrumNote;
import objects.playfields.PlayField;
import shaders.RGBPalette.RGBShaderReference;
import flixel.FlxBasic;
import flixel.group.FlxGroup;
import flixel.util.FlxDestroyUtil;

/**
 * A pool system for managing Note objects to reduce memory allocations and improve performance.
 * Instead of creating new Note instances every time, this pool reuses existing ones.
 */
class NotePool extends FlxBasic
{
	/**
	 * The maximum number of notes to keep in the pool when not in use
	 */
	public static var MAX_POOL_SIZE:Int = 200;
	
	/**
	 * The minimum number of notes to keep in the pool for immediate reuse
	 */
	public static var MIN_POOL_SIZE:Int = 50;
	
	/**
	 * Pool for regular notes
	 */
	private var _notePool:Array<Note>;
	
	/**
	 * Pool for sustain notes
	 */
	private var _sustainPool:Array<Note>;
	
	/**
	 * Array of all active notes currently in use
	 */
	private var _activeNotes:Array<Note>;
	
	/**
	 * Array of all active sustain notes currently in use
	 */
	private var _activeSustains:Array<Note>;
	
	/**
	 * Total number of notes created by this pool
	 */
	public var totalCreated:Int = 0;
	
	/**
	 * Total number of notes reused from the pool
	 */
	public var totalReused:Int = 0;
	
	/**
	 * Whether the pool is currently enabled
	 */
	public var enabled:Bool = true;
	
	public function new()
	{
		super();
		
		// Initialize pools
		_notePool = [];
		_sustainPool = [];
		
		// Initialize active arrays
		_activeNotes = [];
		_activeSustains = [];
		
		// Pre-populate pools with minimum notes
		prePopulatePool();
	}
	
	/**
	 * Pre-populate the pools with minimum required notes
	 */
	private function prePopulatePool():Void
	{
		// Pre-create minimum regular notes
		for (i in 0...MIN_POOL_SIZE)
		{
			var note:Note = createNote();
			_notePool.push(note);
		}
		
		// Pre-create minimum sustain notes
		for (i in 0...MIN_POOL_SIZE)
		{
			var sustain:Note = createSustainNote();
			_sustainPool.push(sustain);
		}
	}
	
	/**
	 * Create a new regular note for the pool
	 */
	private function createNote():Note
	{
		totalCreated++;
		return new Note(0, 0, null, false, false);
	}
	
	/**
	 * Create a new sustain note for the pool
	 */
	private function createSustainNote():Note
	{
		totalCreated++;
		return new Note(0, 0, null, true, false);
	}
	
	/**
	 * Reset a regular note when returning it to the pool
	 */
	private function resetNote(note:Note):Void
	{
		if (note == null) return;
		
		// Reset all note properties to default values
		note.strumTime = 0;
		note.noteData = 0;
		note.mustPress = false;
		note.canBeHit = false;
		note.tooLate = false;
		note.wasGoodHit = false;
		note.missed = false;
		note.ignoreNote = false;
		note.hitByOpponent = false;
		note.noteWasHit = false;
		note.spawned = false;
		note.blockHit = false;
		note.sustainLength = 0;
		note.noteType = null;
		note.eventName = '';
		note.eventLength = 0;
		note.eventVal1 = '';
		note.eventVal2 = '';
		note.animSuffix = '';
		note.gfNote = false;
		note.earlyHitMult = 1;
		note.lateHitMult = 1;
		note.lowPriority = false;
		note.offsetAngle = 0;
		note.multSpeed = 1;
		note.beat = 0;
		note.copyX = true;
		note.copyY = true;
		note.copyAlpha = true;
		note.alphaMod = 1;
		note.alphaMod2 = 1;
		note.hitHealth = 0.02;
		note.missHealth = 0.1;
		note.rating = 'unknown';
		note.ratingMod = 0;
		note.ratingDisabled = false;
		note.noAnimation = false;
		note.noMissAnimation = false;
		note.hitCausesMiss = false;
		note.distance = 2000;
		note.botNote = false;
		note.downscrollNote = ClientPrefs.data.downScroll;
		note.baseAlpha = 1;
		note.autoGenerated = false;
		note.exNote = false;
		note.ghostNote = false;
		note.changeAnim = true;
		note.changeColSwap = true;
		note.spotInLine = 0;
		note.susActive = true;
		note.customHealthHit = false;
		note.centerNote = false;
		note.hitboxMultiplier = 1;
		note.cod = '???';
		note.scrollSpeed = 0;
		note.garbage = false;
		note.holdingTime = 0;
		note.causedMiss = false;
		note.tripProgress = 1;
		note.isHeld = false;
		note.maxReleaseTime = 0.75;
		note.typeOffsetX = 0;
		note.typeOffsetY = 0;
		note.requiresTap = true;
		note.isRoll = false;
		note.holdGlow = true;
		note.visualTime = 0;
		note.fieldIndex = -1;
		note.field = null;
		note.copyVerts = true;
		note.typeOffsetAngle = 0;
		note.istail = false;
		note.AIStrumTime = 0;
		note.AIMiss = false;
		note.hitsoundDisabled = false;
		note.hitsoundChartEditor = true;
		note.hitsoundForce = false;
		note.hitsound = 'hitsound';
		
		// Reset position and visual properties
		note.x = 0;
		note.y = -2000;
		note.alpha = 1;
		note.angle = 0;
		note.scale.set(1, 1);
		note.visible = true;
		note.active = true;
		note.exists = true;
		
		// Clear relationships
		note.prevNote = null;
		note.nextNote = null;
		note.parent = null;
		note.parentNote = null;
		note.childrenNotes = [];
		note.tail = [];
		note.unhitTail = [];
		note.childs = [];
		note.rootNote = null;
		
		// Stop any tweens
		// Note: posTween is private, so we can't access it directly
		
		// Reset Archipelago-specific properties
		note.isMine = false;
		note.isAlert = false;
		note.isHeal = false;
		note.isFreeze = false;
		note.isFakeHeal = false;
		note.trueNoteData = 0;
		note.specialNote = false;
		note.ignoreMiss = false;
		note.spinAmount = 0;
		
		// Reset extra data
		if (note.extraData != null)
		{
			note.extraData.clear();
			note.extraData = null;
		}
		
		// Note: group management should be handled by the calling code
	}
	
	/**
	 * Reset a sustain note when returning it to the pool
	 */
	private function resetSustainNote(note:Note):Void
	{
		resetNote(note); // Use the same reset logic
		note.isSustainNote = true; // Ensure it stays marked as sustain
		note.alpha = 0.6;
		note.multAlpha = 0.6;
		note.hitsoundDisabled = true;
		note.istail = true;
		note.earlyHitMult = 0;
	}
	
	/**
	 * Get a note from the pool
	 * @param strumTime The time when the note should be hit
	 * @param noteData The note data (direction/lane)
	 * @param prevNote The previous note in the sequence
	 * @param sustainNote Whether this is a sustain note
	 * @param inEditor Whether this note is being created in the editor
	 * @param createdFrom The object that created this note
	 * @return A Note instance ready to use
	 */
	public function getNote(strumTime:Float, noteData:Int, ?prevNote:Note, ?sustainNote:Bool = false, ?inEditor:Bool = false, ?createdFrom:Dynamic = null):Note
	{
		if (!enabled)
		{
			// If pool is disabled, create new note normally
			return new Note(strumTime, noteData, prevNote, sustainNote, inEditor, createdFrom);
		}
		
		var note:Note;
		
		if (sustainNote)
		{
			if (_sustainPool.length > 0)
			{
				note = _sustainPool.pop();
				totalReused++;
			}
			else
			{
				note = createSustainNote();
			}
			_activeSustains.push(note);
		}
		else
		{
			if (_notePool.length > 0)
			{
				note = _notePool.pop();
				totalReused++;
			}
			else
			{
				note = createNote();
			}
			_activeNotes.push(note);
		}
		
		// Re-initialize the note with new parameters
		initializeNote(note, strumTime, noteData, prevNote, sustainNote, inEditor, createdFrom);
		
		return note;
	}
	
	/**
	 * Initialize a pooled note with new parameters
	 */
	private function initializeNote(note:Note, strumTime:Float, noteData:Int, ?prevNote:Note, ?sustainNote:Bool = false, ?inEditor:Bool = false, ?createdFrom:Dynamic = null):Void
	{
		if (createdFrom == null) createdFrom = PlayState.instance;
		
		// Set basic properties
		note.strumTime = strumTime;
		note.noteData = noteData;
		note.column = noteData;
		note.prevNote = prevNote;
		note.isSustainNote = sustainNote;
		note.inEditor = inEditor;
		note.moves = false;
		note.beat = Conductor.getBeat(strumTime);
		note.objType = NOTE;
		
		// Handle sustain note relationships
		if (sustainNote && prevNote != null)
		{
			note.parentNote = prevNote;
			while (note.parentNote.parentNote != null)
				note.parentNote = note.parentNote.parentNote;
			note.parentNote.childrenNotes.push(note);
		}
		else if (!sustainNote)
		{
			note.parentNote = null;
		}
		
		// Set position
		note.x = (ClientPrefs.data.middleScroll ? PlayState.STRUM_X_MIDDLESCROLL : PlayState.STRUM_X) + 50;
		if (!sustainNote) note.y = -2000;
		
		// Apply note offset
		if (!inEditor)
		{
			note.strumTime += ClientPrefs.data.noteOffset;
			note.visualTime = PlayState.instance.getNoteInitialTime(note.strumTime);
		}
		
		// Set up RGB shader and texture
		if (noteData > -1)
		{
			if (note.rgbShader == null)
				note.rgbShader = new RGBShaderReference(note, Note.initializeGlobalRGBShader(noteData));
			else
				note.rgbShader.parent = Note.initializeGlobalRGBShader(noteData);
				
			if (PlayState.SONG != null && PlayState.SONG.disableNoteRGB)
				note.rgbShader.enabled = false;
			else
				note.rgbShader.enabled = true;
				
			note.texture = '';
			note.x += Note.swagWidth * (noteData % Note.ammo[PlayState.mania]);
			
			// Play animation
			if (!sustainNote && noteData > -1 && noteData < Note.maxManiaUI_integer)
			{
				var animToPlay:String = Note.keysShit.get(PlayState.mania).get('letters')[noteData];
				if (note.hasAnimation(animToPlay))
					note.animation.play(animToPlay);
				else
				{
					animToPlay = Note.colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]];
					note.animation.play(animToPlay + 'Scroll');
				}
			}
		}
		
		// Link to previous note
		if (prevNote != null)
			prevNote.nextNote = note;
		
		// Handle sustain note specific setup
		if (sustainNote && prevNote != null)
		{
			note.alpha = 0.6;
			note.multAlpha = 0.6;
			note.hitsoundDisabled = true;
			if (ClientPrefs.data.downScroll) note.flipY = true;
			
			note.istail = true;
			
			// Set up sustain animations
			var animToPlay:String = Note.keysShit.get(PlayState.mania).get('letters')[noteData] + ' tail';
			if (!note.hasAnimation(animToPlay))
			{
				animToPlay = Note.colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + 'holdend';
			}
			note.animation.play(animToPlay);
			
			note.updateHitbox();
			note.centerOffsets();
			
			// Handle previous note sustain setup
			if (prevNote.isSustainNote)
			{
				var animToPlay2:String = Note.keysShit.get(PlayState.mania).get('letters')[noteData] + ' hold';
				if (!note.hasAnimation(animToPlay2))
				{
					animToPlay2 = Note.colArray[Note.keysShit.get(PlayState.mania).get('colArray')[noteData]] + 'hold';
				}
				prevNote.animation.play(animToPlay2);
				
				prevNote.scale.y *= Conductor.stepCrochet / 100 * 1.05;
				if (createdFrom != null && createdFrom.songSpeed != null)
					prevNote.scale.y *= createdFrom.songSpeed;
				
				if (PlayState.isPixelStage)
				{
					prevNote.scale.y *= 1.19;
					prevNote.scale.y *= (6 / prevNote.height);
				}
				prevNote.updateHitbox();
				prevNote.centerOffsets();
			}
			
			if (PlayState.isPixelStage)
			{
				note.scale.y *= PlayState.daPixelZoom;
				note.updateHitbox();
				note.centerOffsets();
			}
			note.earlyHitMult = 0;
		}
		else if (!sustainNote)
		{
			note.centerOffsets();
			note.centerOrigin();
			note.centerOffsets();
		}
	}
	
	/**
	 * Return a note to the pool
	 * @param note The note to return
	 */
	public function returnNote(note:Note):Void
	{
		if (!enabled || note == null) return;
		
		// Remove from active arrays
		if (note.isSustainNote)
		{
			_activeSustains.remove(note);
			resetSustainNote(note);
			if (_sustainPool.length < MAX_POOL_SIZE)
			{
				_sustainPool.push(note);
			}
		}
		else
		{
			_activeNotes.remove(note);
			resetNote(note);
			if (_notePool.length < MAX_POOL_SIZE)
			{
				_notePool.push(note);
			}
		}
	}
	
	/**
	 * Return multiple notes to the pool
	 * @param notes Array of notes to return
	 */
	public function returnNotes(notes:Array<Note>):Void
	{
		if (!enabled || notes == null) return;
		
		for (note in notes)
		{
			returnNote(note);
		}
	}
	
	/**
	 * Clear all active notes and return them to the pool
	 */
	public function clearActiveNotes():Void
	{
		if (!enabled) return;
		
		// Return all active notes to pool
		for (note in _activeNotes)
		{
			resetNote(note);
			if (_notePool.length < MAX_POOL_SIZE)
			{
				_notePool.push(note);
			}
		}
		_activeNotes = [];
		
		// Return all active sustains to pool
		for (note in _activeSustains)
		{
			resetSustainNote(note);
			if (_sustainPool.length < MAX_POOL_SIZE)
			{
				_sustainPool.push(note);
			}
		}
		_activeSustains = [];
	}
	
	/**
	 * Get pool statistics
	 * @return Object containing pool statistics
	 */
	public function getStats():Dynamic
	{
		return {
			totalCreated: totalCreated,
			totalReused: totalReused,
			activeNotes: _activeNotes.length,
			activeSustains: _activeSustains.length,
			pooledNotes: _notePool.length,
			pooledSustains: _sustainPool.length,
			efficiency: totalReused > 0 ? (totalReused / (totalCreated + totalReused)) * 100 : 0
		};
	}
	
	/**
	 * Enable or disable the pool
	 * @param enabled Whether to enable the pool
	 */
	public function setEnabled(enabled:Bool):Void
	{
		this.enabled = enabled;
		
		if (!enabled)
		{
			// Clear the pool if disabled
			clearActiveNotes();
		}
	}
	
	/**
	 * Resize the pool capacity
	 * @param maxSize New maximum pool size
	 */
	public function resize(maxSize:Int):Void
	{
		MAX_POOL_SIZE = maxSize;
		// Note: FlxPool doesn't have a direct resize method, so we'll just update the static value
		// New pools will use this size
	}
	
	/**
	 * Clean up the pool
	 */
	override public function destroy():Void
	{
		clearActiveNotes();
		
		// Clear the pools
		if (_notePool != null)
		{
			for (note in _notePool)
			{
				if (note != null) note.destroy();
			}
			_notePool = null;
		}
		
		if (_sustainPool != null)
		{
			for (note in _sustainPool)
			{
				if (note != null) note.destroy();
			}
			_sustainPool = null;
		}
		
		_activeNotes = null;
		_activeSustains = null;
		
		super.destroy();
	}
	
	/**
	 * Get the number of active notes
	 * @return Total number of active notes
	 */
	public function getActiveCount():Int
	{
		return _activeNotes.length + _activeSustains.length;
	}
	
	/**
	 * Get the number of pooled notes
	 * @return Total number of pooled notes
	 */
	public function getPooledCount():Int
	{
		return _notePool.length + _sustainPool.length;
	}
}

/**
 * A template for creating pre-configured notes that can be used by the NotePool
 */
class NoteTemplate
{
	public var strumTime:Float;
	public var noteData:Int;
	public var sustainNote:Bool;
	public var noteType:String;
	public var mustPress:Bool;
	public var eventName:String;
	public var eventVal1:String;
	public var eventVal2:String;
	public var customData:Map<String, Dynamic>;
	
	public function new(strumTime:Float, noteData:Int, ?sustainNote:Bool = false, ?noteType:String = null, ?mustPress:Bool = false)
	{
		this.strumTime = strumTime;
		this.noteData = noteData;
		this.sustainNote = sustainNote;
		this.noteType = noteType;
		this.mustPress = mustPress;
		this.eventName = '';
		this.eventVal1 = '';
		this.eventVal2 = '';
		this.customData = new Map<String, Dynamic>();
	}
	
	/**
	 * Set custom data for this note template
	 */
	public function setCustomData(key:String, value:Dynamic):NoteTemplate
	{
		customData.set(key, value);
		return this;
	}
	
	/**
	 * Set event data for this note template
	 */
	public function setEventData(eventName:String, val1:String = '', val2:String = ''):NoteTemplate
	{
		this.eventName = eventName;
		this.eventVal1 = val1;
		this.eventVal2 = val2;
		return this;
	}
	
	/**
	 * Apply this template to a note from the pool
	 */
	public function applyToNote(note:Note):Void
	{
		if (note == null) return;
		
		// Apply template properties
		note.strumTime = strumTime;
		note.noteData = noteData;
		note.column = noteData;
		note.isSustainNote = sustainNote;
		note.mustPress = mustPress;
		
		if (noteType != null && noteType.length > 0)
			note.noteType = noteType;
		
		if (eventName.length > 0)
		{
			note.eventName = eventName;
			note.eventVal1 = eventVal1;
			note.eventVal2 = eventVal2;
		}
		
		// Apply custom data
		for (key in customData.keys())
		{
			var value = customData.get(key);
			try
			{
				Reflect.setField(note, key, value);
			}
			catch (e:Dynamic)
			{
				trace('Could not set custom data field: $key = $value');
			}
		}
	}
	
	/**
	 * Create a copy of this template
	 */
	public function clone():NoteTemplate
	{
		var template = new NoteTemplate(strumTime, noteData, sustainNote, noteType, mustPress);
		template.eventName = eventName;
		template.eventVal1 = eventVal1;
		template.eventVal2 = eventVal2;
		
		// Copy custom data
		for (key in customData.keys())
		{
			template.customData.set(key, customData.get(key));
		}
		
		return template;
	}
}

// Abstract for seamless conversion between Note, NoteTemplate, and NoteTemplateI
abstract NoteTemplateI(NoteTemplate) from NoteTemplate to NoteTemplate
{
    // Allow implicit conversion from Note to NoteTemplateI
    @:from
    public static function fromNote(note:Note):NoteTemplateI
    {
        var template = new NoteTemplate(note.strumTime, note.noteData, note.isSustainNote, note.noteType, note.mustPress);
        template.eventName = note.eventName;
        template.eventVal1 = note.eventVal1;
        template.eventVal2 = note.eventVal2;

        // Copy important properties
        template.setCustomData('gfNote', note.gfNote);
        template.setCustomData('botNote', note.botNote);
        template.setCustomData('hitCausesMiss', note.hitCausesMiss);
        template.setCustomData('lowPriority', note.lowPriority);
        template.setCustomData('ignoreNote', note.ignoreNote);
        template.setCustomData('animSuffix', note.animSuffix);
        template.setCustomData('earlyHitMult', note.earlyHitMult);
        template.setCustomData('lateHitMult', note.lateHitMult);
        template.setCustomData('hitHealth', note.hitHealth);
        template.setCustomData('missHealth', note.missHealth);
        template.setCustomData('noAnimation', note.noAnimation);
        template.setCustomData('noMissAnimation', note.noMissAnimation);
        template.setCustomData('hitsound', note.hitsound);
        template.setCustomData('hitsoundVolume', note.hitsoundVolume);

        return cast template;
    }

    // Allow implicit conversion from NoteTemplate to NoteTemplateI
    @:from
    public static function fromNoteTemplate(template:NoteTemplate):NoteTemplateI
    {
        return cast template;
    }

    // Allow implicit conversion to NoteTemplate
    @:to
    public function toNoteTemplate():NoteTemplate
    {
        return this;
    }

    // Allow implicit conversion to Note
    @:to
    public function toNote():Note
    {
        var note = new Note(this.strumTime, this.noteData, null, this.sustainNote, this.mustPress);
        this.applyToNote(note);
        return note;
    }
}

/**
 * Abstract type that allows Arrays of Notes to be used as a waiting pool for NotePool
 */
abstract AbstractNoteArray(Array<NoteTemplate>) from Array<NoteTemplate> to Array<NoteTemplate>
{
	public function new(?notes:Array<NoteTemplate>)
	{
		this = notes != null ? notes : [];
	}
	
	/**
	 * Create from an array of regular Notes
	 */
	@:from
	public static function fromNoteArray(notes:Array<Note>):AbstractNoteArray
	{
		var templates:Array<NoteTemplate> = [];
		
		for (note in notes)
		{
			if (note == null) continue;
			
			var template = new NoteTemplate(note.strumTime, note.noteData, note.isSustainNote, note.noteType, note.mustPress);
			template.eventName = note.eventName;
			template.eventVal1 = note.eventVal1;
			template.eventVal2 = note.eventVal2;
			
			// Copy important properties
			template.setCustomData('gfNote', note.gfNote);
			template.setCustomData('botNote', note.botNote);
			template.setCustomData('hitCausesMiss', note.hitCausesMiss);
			template.setCustomData('lowPriority', note.lowPriority);
			template.setCustomData('ignoreNote', note.ignoreNote);
			template.setCustomData('animSuffix', note.animSuffix);
			template.setCustomData('earlyHitMult', note.earlyHitMult);
			template.setCustomData('lateHitMult', note.lateHitMult);
			template.setCustomData('hitHealth', note.hitHealth);
			template.setCustomData('missHealth', note.missHealth);
			template.setCustomData('noAnimation', note.noAnimation);
			template.setCustomData('noMissAnimation', note.noMissAnimation);
			template.setCustomData('hitsound', note.hitsound);
			template.setCustomData('hitsoundVolume', note.hitsoundVolume);
			template.setCustomData('hitsoundDisabled', note.hitsoundDisabled);
			
			// Copy Archipelago-specific properties
			template.setCustomData('isMine', note.isMine);
			template.setCustomData('isAlert', note.isAlert);
			template.setCustomData('isHeal', note.isHeal);
			template.setCustomData('isFreeze', note.isFreeze);
			template.setCustomData('isFakeHeal', note.isFakeHeal);
			template.setCustomData('specialNote', note.specialNote);
			template.setCustomData('ignoreMiss', note.ignoreMiss);
			
			templates.push(template);
		}
		
		return new AbstractNoteArray(templates);
	}
	
	/**
	 * Add a note template to the pool
	 */
	public function add(template:NoteTemplate):AbstractNoteArray
	{
		this.push(template);
		return cast this;
	}
	
	/**
	 * Add multiple note templates to the pool
	 */
	public function addAll(templates:Array<NoteTemplate>):AbstractNoteArray
	{
		for (template in templates)
		{
			this.push(template);
		}
		return cast this;
	}
	
	/**
	 * Remove a note template from the pool
	 */
	public function remove(template:NoteTemplate):Bool
	{
		return this.remove(template);
	}

    public function pop():NoteTemplate
    {
        return this.pop();
    }

    public function unshift(note:Note):Void
    {
        return this.unshift(new NoteTemplate(note.strumTime, note.noteData, note.isSustainNote, note.noteType, note.mustPress));
    }

    public function shift():NoteTemplate
    {
        return this.shift();
    }

    public function push(note:Note):Int
    {
        return this.push(new NoteTemplate(note.strumTime, note.noteData, note.isSustainNote, note.noteType, note.mustPress));
    }



	/**
	 * Clear all note templates from the pool
	 */
	public function clear():Void
	{
		this.splice(0, this.length);
	}
	
	/**
	 * Get the number of note templates in the pool
	 */
	public var length(get, never):Int;
	function get_length():Int
	{
		return this.length;
	}
	
	/**
	 * Check if the pool is empty
	 */
	public function isEmpty():Bool
	{
		return this.length == 0;
	}
	
	/**
	 * Get a note template by index
	 */
	public function get(index:Int):NoteTemplate
	{
		return this[index];
	}
	
	/**
	 * Set a note template at a specific index
	 */
	public function set(index:Int, template:NoteTemplate):Void
	{
		this[index] = template;
	}
	
	/**
	 * Get the next note template and remove it from the pool
	 */
	public function getNext():NoteTemplate
	{
		return this.length > 0 ? this.shift() : null;
	}
	
	/**
	 * Peek at the next note template without removing it
	 */
	public function peekNext():NoteTemplate
	{
		return this.length > 0 ? this[0] : null;
	}
	
	/**
	 * Get all note templates with a specific note type
	 */
	public function getByType(noteType:String):Array<NoteTemplate>
	{
		var result:Array<NoteTemplate> = [];
		for (template in this)
		{
			if (template.noteType == noteType)
			{
				result.push(template);
			}
		}
		return result;
	}
	
	/**
	 * Get all note templates within a time range
	 */
	public function getByTimeRange(startTime:Float, endTime:Float):Array<NoteTemplate>
	{
		var result:Array<NoteTemplate> = [];
		for (template in this)
		{
			if (template.strumTime >= startTime && template.strumTime <= endTime)
			{
				result.push(template);
			}
		}
		return result;
	}
	
	/**
	 * Sort note templates by strum time
	 */
	public function sortByTime():AbstractNoteArray
	{
		this.sort(function(a:NoteTemplate, b:NoteTemplate):Int
		{
			return Std.int(a.strumTime - b.strumTime);
		});
		return cast this;
	}
	
	/**
	 * Create actual notes from templates using a note pool
	 */
	public function createNotes(pool:NotePool, ?inEditor:Bool = false, ?createdFrom:Dynamic = null):Array<Note>
	{
		var notes:Array<Note> = [];
		var prevNote:Note = null;
		
		for (template in this)
		{
			var note:Note = pool.getNote(template.strumTime, template.noteData, prevNote, template.sustainNote, inEditor, createdFrom);
			template.applyToNote(note);
			notes.push(note);
			
			if (!template.sustainNote)
			{
				prevNote = note;
			}
		}
		
		return notes;
	}

    @:to
    public function toNoteArray():Array<Note>
    {
        var notes:Array<Note> = [];
        for (template in this)
        {
            var note:Note = new Note(template.strumTime, template.noteData, null, template.sustainNote);
            template.applyToNote(note);
            notes.push(note);
        }
        return notes;
    }
	
	/**
	 * Iterator support
	 */
	public inline function iterator():Iterator<NoteTemplate>
	{
		return this.iterator();
	}
}

// AbstractNoteArray that acts like an Array<Note>, but creates Notes on demand from NoteTemplates.
// This allows PlayState to use it as if it were an Array<Note> without explicit conversion.
abstract NoteArray(AbstractNoteArray) from AbstractNoteArray to AbstractNoteArray {
    public function new(?templates:Array<NoteTemplate>) {
        this = new AbstractNoteArray(templates);
    }

    // Returns the number of notes (same as number of templates)
    public var length(get, never):Int;
    inline function get_length():Int return this.length;

    // Array access: creates a Note from the template at index
    @:arrayAccess
    public inline function get(index:Int):Note {
        var template = this[index];
        if (template == null) return null;
        var note = new Note(template.strumTime, template.noteData, null, template.sustainNote);
        template.applyToNote(note);
        return note;
    }

    // Setting a Note at an index: converts it to a NoteTemplate
    @:arrayAccess
    public inline function set(index:Int, note:Note):Void {
        this[index] = new NoteTemplate(note.strumTime, note.noteData, note.isSustainNote, note.noteType, note.mustPress);
    }

    // Iterator: yields Notes created from templates
    public function iterator():Iterator<Note> {
        var i = 0, len = this.length;
        var arr = this;
        return {
            hasNext: function() return i < len,
            next: function() {
                var template = arr[i++];
                if (template == null) return null;
                var note = new Note(template.strumTime, template.noteData, null, template.sustainNote);
                template.applyToNote(note);
                return note;
            }
        };
    }

    // Push a Note (converted to NoteTemplate)
    public inline function push(note:Note):Int {
        return this.push(note);
    }

    // Pop returns a Note created from the last template
    public inline function pop():Note {
        var template = this.pop();
        if (template == null) return null;
        var note = new Note(template.strumTime, template.noteData, null, template.sustainNote);
        template.applyToNote(note);
        return note;
    }

    // Shift returns a Note created from the first template
    public inline function shift():Note {
        var template = this.shift();
        if (template == null) return null;
        var note = new Note(template.strumTime, template.noteData, null, template.sustainNote);
        template.applyToNote(note);
        return note;
    }

    // Unshift a Note (converted to NoteTemplate)
    public inline function unshift(note:Note):Void {
        return this.unshift(note);
    }

    // Convert to a real Array<Note>
    @:to
    public function toNoteArray():Array<Note> {
        var notes:Array<Note> = [];
        for (template in this) {
            if (template == null) continue;
            var note = new Note(template.strumTime, template.noteData, null, template.sustainNote);
            template.applyToNote(note);
            notes.push(note);
        }
        return notes;
    }
}

/**
 * A specialized note queue system that works with PlayField's nested array structure.
 * Each column has its own array of notes, optimized for PlayField's existing workflow.
 */
class NoteQueue
{
	/**
	 * The underlying nested array structure - one array per column
	 */
	private var _columns:Array<AbstractNoteArray>;
	
	/**
	 * Reference to the note pool for creating notes
	 */
	private var _notePool:NotePool;
	
	/**
	 * Maximum number of columns supported
	 */
	public static var MAX_COLUMNS:Int = 18;
	
	public function new(?notePool:NotePool)
	{
		_notePool = notePool != null ? notePool : new NotePool();
		_columns = [];
		
		// Initialize all columns as empty arrays
		for (i in 0...MAX_COLUMNS)
		{
			_columns[i] = new AbstractNoteArray();
		}
	}
	
	/**
	 * Array access for getting a column
	 */
	@:arrayAccess
	public function get(column:Int):AbstractNoteArray
	{
		if (column < 0 || column >= _columns.length)
			return new AbstractNoteArray(); // Return empty array for invalid columns
		return _columns[column];
	}
	
	/**
	 * Array access for setting a column
	 */
	@:arrayAccess
	public function set(column:Int, notes:AbstractNoteArray):Void
	{
		if (column >= 0 && column < _columns.length)
			_columns[column] = notes;
	}
	
	/**
	 * Push a note template to a specific column
	 */
	public function push(column:Int, template:NoteTemplate):Void
	{
		if (column >= 0 && column < _columns.length)
		{
			_columns[column].add(template);
			_columns[column].sortByTime();
		}
	}
	
	/**
	 * Push a regular Note to a specific column (converts to template)
	 */
	public function pushNote(column:Int, note:Note):Void
	{
		if (column >= 0 && column < _columns.length)
		{
			var template = new NoteTemplate(note.strumTime, note.noteData, note.isSustainNote, note.noteType, note.mustPress);
			template.eventName = note.eventName;
			template.eventVal1 = note.eventVal1;
			template.eventVal2 = note.eventVal2;
			
			// Copy important properties
			template.setCustomData('gfNote', note.gfNote);
			template.setCustomData('botNote', note.botNote);
			template.setCustomData('hitCausesMiss', note.hitCausesMiss);
			template.setCustomData('lowPriority', note.lowPriority);
			template.setCustomData('ignoreNote', note.ignoreNote);
			
			_columns[column].add(template);
			_columns[column].sortByTime();
		}
	}
	
	/**
	 * Remove a template from a specific column
	 */
	public function remove(column:Int, template:NoteTemplate):Bool
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].remove(template);
		return false;
	}
	
	/**
	 * Get the first template from a column and remove it
	 */
	public function shift(column:Int):NoteTemplate
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].getNext();
		return null;
	}
	
	/**
	 * Peek at the first template in a column without removing it
	 */
	public function peek(column:Int):NoteTemplate
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].peekNext();
		return null;
	}
	
	/**
	 * Get the length of a specific column
	 */
	public function length(column:Int):Int
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].length;
		return 0;
	}
	
	/**
	 * Check if a column is empty
	 */
	public function isEmpty(column:Int):Bool
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].isEmpty();
		return true;
	}
	
	/**
	 * Clear a specific column
	 */
	public function clear(column:Int):Void
	{
		if (column >= 0 && column < _columns.length)
			_columns[column].clear();
	}
	
	/**
	 * Clear all columns
	 */
	public function clearAll():Void
	{
		for (column in _columns)
			column.clear();
	}
	
	/**
	 * Sort a specific column by time
	 */
	public function sort(column:Int):Void
	{
		if (column >= 0 && column < _columns.length)
			_columns[column].sortByTime();
	}
	
	/**
	 * Sort all columns by time
	 */
	public function sortAll():Void
	{
		for (column in _columns)
			column.sortByTime();
	}
	
	/**
	 * Create actual notes from templates in a specific column
	 */
	public function createNotes(column:Int, ?inEditor:Bool = false, ?createdFrom:Dynamic = null):Array<Note>
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].createNotes(_notePool, inEditor, createdFrom);
		return [];
	}
	
	/**
	 * Create a single note from the next template in a column
	 */
	public function createNextNote(column:Int, ?prevNote:Note, ?inEditor:Bool = false, ?createdFrom:Dynamic = null):Note
	{
		var template = shift(column);
		if (template != null)
			var note = _notePool.getNote(template.strumTime, template.noteData, prevNote, template.sustainNote, inEditor, createdFrom);
			template.applyToNote(note);
			return note;
		return null;
	}
	
	/**
	 * Get templates in a specific time range for a column
	 */
	public function getByTimeRange(column:Int, startTime:Float, endTime:Float):Array<NoteTemplate>
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].getByTimeRange(startTime, endTime);
		return [];
	}
	
	/**
	 * Get templates by note type for a column
	 */
	public function getByType(column:Int, noteType:String):Array<NoteTemplate>
	{
		if (column >= 0 && column < _columns.length)
			return _columns[column].getByType(noteType);
		return [];
	}
	
	/**
	 * Convert to the old Array<Array<Note>> format for compatibility
	 */
	@:to
	public function toNoteArrays():Array<Array<Note>>
	{
		var result:Array<Array<Note>> = [];
		for (i in 0...MAX_COLUMNS)
		{
			result[i] = createNotes(i);
		}
		return result;
	}
	
	/**
	 * Create from an existing Array<Array<Note>> structure
	 */
	@:from
	public static function fromNoteArrays(noteArrays:Array<Array<Note>>):NoteQueue
	{
		var queue = new NoteQueue();
		
		for (column in 0...noteArrays.length)
		{
			if (noteArrays[column] != null)
			{
				for (note in noteArrays[column])
				{
					if (note != null)
						queue.pushNote(column, note);
				}
			}
		}
		
		return queue;
	}
	
	/**
	 * Get total number of templates across all columns
	 */
	public function getTotalCount():Int
	{
		var total = 0;
		for (column in _columns)
			total += column.length;
		return total;
	}
	
	/**
	 * Get statistics for the queue
	 */
	public function getStats():Dynamic
	{
		var columnCounts:Array<Int> = [];
		var totalNotes = 0;
		
		for (i in 0..._columns.length)
		{
			columnCounts[i] = _columns[i].length;
			totalNotes += columnCounts[i];
		}
		
		return {
			totalNotes: totalNotes,
			columnCounts: columnCounts,
			poolStats: _notePool.getExtendedStats()
		};
	}
	
	/**
	 * Set the note pool to use
	 */
	public function setNotePool(pool:NotePool):Void
	{
		_notePool = pool;
	}
	
	/**
	 * Get the note pool being used
	 */
	public function getNotePool():NotePool
	{
		return _notePool;
	}
	
	/**
	 * Iterator support for iterating over all columns
	 */
	public function iterator():Iterator<AbstractNoteArray>
	{
		return _columns.iterator();
	}
}

/**
 * Abstract type that provides seamless compatibility with PlayField's existing noteQueue
 * Can be used as a drop-in replacement for Array<Array<Note>>
 */
abstract PlayFieldNoteQueue(NoteQueue) from NoteQueue to NoteQueue
{
	public function new(?notePool:NotePool)
	{
		this = new NoteQueue(notePool);
	}
	
	/**
	 * Array access - get a column as AbstractNoteArray
	 */
	@:arrayAccess
	public function get(column:Int):AbstractNoteArray
	{
		return this[column];
	}
	
	/**
	 * Array access - set a column
	 */
	@:arrayAccess
	public function set(column:Int, notes:AbstractNoteArray):Void
	{
		this[column] = notes;
	}
	
	/**
	 * Convert from existing Array<Array<Note>> structure
	 */
	@:from
	public static function fromNoteArrays(noteArrays:Array<Array<Note>>):PlayFieldNoteQueue
	{
		return NoteQueue.fromNoteArrays(noteArrays);
	}
	
	/**
	 * Convert to Array<Array<Note>> for compatibility
	 */
	@:to
	public function toNoteArrays():Array<Array<Note>>
	{
		return this.toNoteArrays();
	}
	
	/**
	 * Push a note to a specific column (compatibility method)
	 */
	public function push(column:Int, note:Note):Void
	{
		this.pushNote(column, note);
	}
	
	/**
	 * Remove a note from a specific column (finds by matching properties)
	 */
	public function remove(column:Int, note:Note):Bool
	{
		var templates = this[column];
		for (template in templates)
		{
			if (template.strumTime == note.strumTime && 
				template.noteData == note.noteData && 
				template.sustainNote == note.isSustainNote)
			{
				return this.remove(column, template);
			}
		}
		return false;
	}
	
	/**
	 * Sort a column by strum time
	 */
	public function sort(column:Int, ?sortFunction:(NoteTemplate, NoteTemplate) -> Int):Void
	{
		if (sortFunction == null)
			this.sort(column);
		else
		{
			// Custom sort function support
			var columnArray = this[column];
			// Note: AbstractNoteArray would need a custom sort method for this to work fully
			// For now, just use the default time sort
			this.sort(column);
		}
	}
	
	/**
	 * Get length of a specific column
	 */
	public function length(column:Int):Int
	{
		return this.length(column);
	}
	
	/**
	 * Check if empty
	 */
	public function isEmpty(column:Int):Bool
	{
		return this.isEmpty(column);
	}
	
	/**
	 * Clear all columns
	 */
	public function clear():Void
	{
		this.clearAll();
	}

    public function iterator():Iterator<AbstractNoteArray>
    {
        return this.iterator();
}

}
