package yutautil.typeregistry;

import haxe.Json;
import sys.FileSystem;
import sys.io.File;

/**
 * Build-time data loader that provides access to macro-generated metadata
 * Works with data generated by macros.BuildMacro
 */
class BuildDataLoader {
    static var loadedData:Dynamic = null;
    static var isInitialized:Bool = false;
    static var dataPath:String = "export/builddata/type_collection_compressed.json";
    static var fullDataPath:String = "export/builddata/type_collection_data.json";

    /**
     * Initialize the build data loader
     * Attempts to load compressed data first, then full data as fallback
     */
    public static function initialize():Bool {
        if (isInitialized) return true;

        try {
            // Try to load compressed data first
            if (FileSystem.exists(dataPath)) {
                var content = File.getContent(dataPath);
                loadedData = Json.parse(content);
                trace('BuildDataLoader: Loaded compressed build data from $dataPath');
                isInitialized = true;
                return true;
            }

            // Fallback to full data
            if (FileSystem.exists(fullDataPath)) {
                var content = File.getContent(fullDataPath);
                loadedData = Json.parse(content);
                trace('BuildDataLoader: Loaded full type collection data from $fullDataPath');
                isInitialized = true;
                return true;
            }

            trace('BuildDataLoader: No type collection data found - build macro may not have run');
            return false;
        }
    }

    /**
     * Get all class names from build data
     */
    public static function getAllClasses():Array<String> {
        if (!ensureInitialized()) return [];

        try {
            var classes:Array<Dynamic> = loadedData.classes;
            return [for (cls in classes) '${cls.pack}.${cls.name}'];
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting classes: $e');
            return [];
        }
    }

    /**
     * Get all abstract names from build data
     */
    public static function getAllAbstracts():Array<String> {
        if (!ensureInitialized()) return [];

        try {
            var abstracts:Array<Dynamic> = loadedData.abstracts;
            return [for (abs in abstracts) '${abs.pack}.${abs.name}'];
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting abstracts: $e');
            return [];
        }
    }

    /**
     * Get all typedef names from build data
     */
    public static function getAllTypedefs():Array<String> {
        if (!ensureInitialized()) return [];

        try {
            var typedefs:Array<Dynamic> = loadedData.typedefs;
            return [for (td in typedefs) '${td.pack}.${td.name}'];
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting typedefs: $e');
            return [];
        }
    }

    /**
     * Get all function information from build data
     */
    public static function getAllFunctions():Array<Dynamic> {
        if (!ensureInitialized()) return [];

        try {
            return cast loadedData.functions;
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting functions: $e');
            return [];
        }
    }

    /**
     * Get class information by name
     */
    public static function getClassInfo(className:String):Dynamic {
        if (!ensureInitialized()) return null;

        try {
            var classes:Array<Dynamic> = loadedData.classes;
            for (cls in classes) {
                var fullName = '${cls.pack}.${cls.name}';
                if (fullName == className || cls.name == className) {
                    return cls;
                }
            }
            return null;
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting class info: $e');
            return null;
        }
    }

    /**
     * Get abstract information by name
     */
    public static function getAbstractInfo(abstractName:String):Dynamic {
        if (!ensureInitialized()) return null;

        try {
            var abstracts:Array<Dynamic> = loadedData.abstracts;
            for (abs in abstracts) {
                var fullName = '${abs.pack}.${abs.name}';
                if (fullName == abstractName || abs.name == abstractName) {
                    return abs;
                }
            }
            return null;
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting abstract info: $e');
            return null;
        }
    }

    /**
     * Get functions by class name
     */
    public static function getFunctionsByClass(className:String):Array<Dynamic> {
        if (!ensureInitialized()) return [];

        try {
            var functions:Array<Dynamic> = loadedData.functions;
            return functions.filter(f -> f.className == className);
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting functions by class: $e');
            return [];
        }
    }

    /**
     * Search functions by name pattern
     */
    public static function searchFunctions(pattern:String):Array<Dynamic> {
        if (!ensureInitialized()) return [];

        try {
            var functions:Array<Dynamic> = loadedData.functions;
            return functions.filter(f -> f.name.indexOf(pattern) != -1);
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error searching functions: $e');
            return [];
        }
    }

    /**
     * Get functions with specific metadata
     */
    public static function getFunctionsWithMetadata(metadata:String):Array<Dynamic> {
        if (!ensureInitialized()) return [];

        try {
            var functions:Array<Dynamic> = loadedData.functions;
            return functions.filter(f -> {
                var meta:Array<String> = f.metadata;
                return meta.filter(m -> m.indexOf(metadata) != -1).length > 0;
            });
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting functions with metadata: $e');
            return [];
        }
    }

    /**
     * Get build statistics
     */
    public static function getBuildStats():Dynamic {
        if (!ensureInitialized()) return null;

        try {
            return {
                timestamp: loadedData.timestamp,
                platform: loadedData.platform,
                classCount: loadedData.classes.length,
                abstractCount: loadedData.abstracts.length,
                functionCount: loadedData.functions.length,
                sourceFileCount: loadedData.sourceFileCount != null ? loadedData.sourceFileCount : 0
            };
        } catch (e:Dynamic) {
            trace('BuildDataLoader: Error getting build stats: $e');
            return null;
        }
    }

    /**
     * Get all available type names
     */
    public static function getAllTypeNames():Array<String> {
        var types:Array<String> = [];
        types = types.concat(getAllClasses());
        types = types.concat(getAllAbstracts());
        types = types.concat(getAllTypedefs());
        return types;
    }

    /**
     * Check if a type exists in the build data
     */
    public static function hasType(typeName:String):Bool {
        return getAllTypeNames().indexOf(typeName) != -1;
    }

    /**
     * Get detailed type information (works for classes, abstracts, typedefs)
     */
    public static function getTypeInfo(typeName:String):Dynamic {
        var classInfo = getClassInfo(typeName);
        if (classInfo != null) return {type: "class", data: classInfo};

        var abstractInfo = getAbstractInfo(typeName);
        if (abstractInfo != null) return {type: "abstract", data: abstractInfo};

        // Try typedefs if we have full data
        if (!ensureInitialized()) return null;

        try {
            var typedefs:Array<Dynamic> = loadedData.typedefs;
            if (typedefs != null) {
                for (td in typedefs) {
                    var fullName = '${td.pack}.${td.name}';
                    if (fullName == typeName || td.name == typeName) {
                        return {type: "typedef", data: td};
                    }
                }
            }
        } catch (e:Dynamic) {
            // Typedef data might not be in compressed version
        }

        return null;
    }

    /**
     * Get raw loaded data (for advanced usage)
     */
    public static function getRawData():Dynamic {
        ensureInitialized();
        return loadedData;
    }

    /**
     * Force reload build data
     */
    public static function reload():Bool {
        isInitialized = false;
        loadedData = null;
        return initialize();
    }

    static function ensureInitialized():Bool {
        if (!isInitialized) {
            return initialize();
        }
        return true;
    }
}

/**
 * Enhanced type info structure for build data
 */
typedef BuildTypeInfo = {
    name: String,
    pack: String,
    ?fields: Array<String>,
    ?type: String,
    ?confidence: Float
}
