package backend;

@:build(macros.VersionMacro.build())
class Version {
    // Version constants will be generated by the macro:
    // ENGINE_VERSION - Version string from gitVersion.txt or Project.xml
    // ENGINE_BETA - Beta version string
    // BUILD_NUMBER - Auto-incrementing build number
    // BUILD_DATE - Build compilation date
    // SEMANTIC_VERSION - SemanticVersion abstract for comparisons
    // getVersionString(includeBuild) - Formatted version string
    // getFullVersionInfo() - Complete version info with build date
    // compareVersion(otherVersion) - Compare current version with another

    /**
     * Get individual version components
     */
    public static function getMajor():Int {
        return SEMANTIC_VERSION.major;
    }

    public static function getMinor():Int {
        return SEMANTIC_VERSION.minor;
    }

    public static function getPatch():Int {
        return SEMANTIC_VERSION.patch;
    }

    public static function getBeta():String {
        return SEMANTIC_VERSION.beta;
    }

    /**
     * Check if current version is newer than specified version
     */
    public static function isNewerThan(version:String):Bool {
        return compareVersion(version) > 0;
    }

    /**
     * Check if current version is older than specified version
     */
    public static function isOlderThan(version:String):Bool {
        return compareVersion(version) < 0;
    }

    /**
     * Check if current version equals specified version
     */
    public static function isEqualTo(version:String):Bool {
        return compareVersion(version) == 0;
    }

    /**
     * Get version without beta suffix
     */
    public static function getVersionOnly():String {
        return ENGINE_VERSION;
    }

    /**
     * Get beta suffix only
     */
    public static function getBetaOnly():String {
        return ENGINE_BETA;
    }
}

// Export the SemanticVersion abstract for external use
typedef SemanticVersion = macros.VersionMacro.SemanticVersion;
